import { useLang, type Lang } from "@/lib/i18n";

const en = {
  lblCertName: "Certification name", lblCertId: "Certificate ID", lblCertOrg: "Certificate issuing organization",
  lblCertIssue: "Certificate issue date", lblCertExpiry: "Certificate expiry date", lblUpload: "Upload certificate (optional)",
  submit: "Submit for verification",
  st_not_verified: "NOT VERIFIED", st_pending: "PENDING REVIEW", st_verified: "✓ VERIFIED", st_rejected: "REJECTED",
  demoVerif: "DEMO VERIFICATION",
  reviewTitle: "Certificate review", noDoc: "No certificate uploaded.", openDoc: "Open document",
  manualNote: "Text extraction is not available in this prototype. The reviewer enters or corrects the certificate details below. Prototype data.",
  saveDetails: "Save details",
  checklistTitle: "Verification checklist",
  ck_doc: "Certificate document uploaded", ck_id: "Certificate ID present", ck_name: "Certification name recorded",
  ck_org: "Issuing organization recorded", ck_issue: "Issue date recorded", ck_expiry: "Expiry date recorded",
  ck_notExpired: "Certificate is not expired", ck_external: "External licensing-authority verification",
  ckExternalNote: "External authority verification is NOT connected in this prototype.",
  markVerified: "Mark as verified", requestReview: "Request review", reject: "Reject",
  onlyReviewer: "Only a reviewer action changes this status. Uploading a file or completing fields does not verify a doctor.",
  verifiedOn: "Verification date", reviewer: "Reviewer", reviewerName: "Demo reviewer", credExpiry: "Credential expiry",
  verifiedNote: "Demo verification only. The doctor's real-world credentials have not been checked against the UAE DoH or any licensing authority.",
  historyTitle: "Verification history and audit trail",
  ev_created: "Synthetic demo record created", ev_added: "Doctor added in this session", ev_submitted: "Submitted for verification",
  ev_uploaded: "Certificate uploaded: {f}", ev_edited: "Reviewer entered or corrected certificate details",
  ev_verify: "Reviewer marked as verified (demo)", ev_request: "Reviewer requested further review", ev_reject: "Reviewer rejected the submission",
  disclaimer: "Credential verification is not performed against an external licensing authority in this prototype. A production deployment would authenticate reviewers and verify credentials against the relevant licensing authority.",
  orgFamily: "Demo Board of Family Medicine", orgEndo: "Demo Board of Endocrinology",
  openReview: "Open certificate review", closeReview: "Close certificate review",
};
export type CredText = typeof en;

const ar: CredText = {
  lblCertName: "اسم الشهادة", lblCertId: "رقم الشهادة", lblCertOrg: "الجهة المانحة للشهادة",
  lblCertIssue: "تاريخ إصدار الشهادة", lblCertExpiry: "تاريخ انتهاء الشهادة", lblUpload: "رفع الشهادة (اختياري)",
  submit: "إرسال للتحقق",
  st_not_verified: "غير موثّق", st_pending: "قيد المراجعة", st_verified: "✓ موثّق", st_rejected: "مرفوض",
  demoVerif: "توثيق تجريبي",
  reviewTitle: "مراجعة الشهادة", noDoc: "لم تُرفع أي شهادة.", openDoc: "فتح المستند",
  manualNote: "استخراج النص غير متاح في هذا النموذج. يُدخل المراجع بيانات الشهادة أو يصححها أدناه. بيانات نموذجية.",
  saveDetails: "حفظ البيانات",
  checklistTitle: "قائمة التحقق",
  ck_doc: "تم رفع مستند الشهادة", ck_id: "رقم الشهادة موجود", ck_name: "اسم الشهادة مسجّل",
  ck_org: "الجهة المانحة مسجّلة", ck_issue: "تاريخ الإصدار مسجّل", ck_expiry: "تاريخ الانتهاء مسجّل",
  ck_notExpired: "الشهادة غير منتهية", ck_external: "التحقق من جهة الترخيص الخارجية",
  ckExternalNote: "التحقق من الجهة الخارجية غير متصل في هذا النموذج.",
  markVerified: "وضع علامة موثّق", requestReview: "طلب مراجعة", reject: "رفض",
  onlyReviewer: "لا يغيّر هذه الحالة إلا إجراء المراجع. رفع ملف أو إكمال الحقول لا يوثّق الطبيب.",
  verifiedOn: "تاريخ التوثيق", reviewer: "المراجع", reviewerName: "مراجع تجريبي", credExpiry: "انتهاء الاعتماد",
  verifiedNote: "توثيق تجريبي فقط. لم يتم التحقق من اعتمادات الطبيب الحقيقية لدى دائرة الصحة أو أي جهة ترخيص.",
  historyTitle: "سجل التحقق ومسار التدقيق",
  ev_created: "أُنشئ سجل تجريبي اصطناعي", ev_added: "أُضيف الطبيب في هذه الجلسة", ev_submitted: "أُرسل للتحقق",
  ev_uploaded: "رُفعت الشهادة: {f}", ev_edited: "أدخل المراجع بيانات الشهادة أو صححها",
  ev_verify: "وضع المراجع علامة موثّق (تجريبي)", ev_request: "طلب المراجع مراجعة إضافية", ev_reject: "رفض المراجع الطلب",
  disclaimer: "لا يتم التحقق من الاعتمادات لدى جهة ترخيص خارجية في هذا النموذج. في النسخة الفعلية يتم توثيق هوية المراجعين والتحقق من الاعتمادات لدى جهة الترخيص المختصة.",
  orgFamily: "مجلس طب الأسرة التجريبي", orgEndo: "مجلس الغدد الصماء التجريبي",
  openReview: "فتح مراجعة الشهادة", closeReview: "إغلاق مراجعة الشهادة",
};

const hi: CredText = {
  lblCertName: "प्रमाणपत्र का नाम", lblCertId: "प्रमाणपत्र आईडी", lblCertOrg: "प्रमाणपत्र जारी करने वाली संस्था",
  lblCertIssue: "प्रमाणपत्र जारी होने की तिथि", lblCertExpiry: "प्रमाणपत्र समाप्ति तिथि", lblUpload: "प्रमाणपत्र अपलोड करें (वैकल्पिक)",
  submit: "सत्यापन के लिए भेजें",
  st_not_verified: "सत्यापित नहीं", st_pending: "समीक्षा लंबित", st_verified: "✓ सत्यापित", st_rejected: "अस्वीकृत",
  demoVerif: "डेमो सत्यापन",
  reviewTitle: "प्रमाणपत्र समीक्षा", noDoc: "कोई प्रमाणपत्र अपलोड नहीं हुआ।", openDoc: "दस्तावेज़ खोलें",
  manualNote: "इस प्रोटोटाइप में टेक्स्ट निकालना उपलब्ध नहीं है। समीक्षक नीचे प्रमाणपत्र विवरण दर्ज या सुधारता है। प्रोटोटाइप डेटा।",
  saveDetails: "विवरण सहेजें",
  checklistTitle: "सत्यापन चेकलिस्ट",
  ck_doc: "प्रमाणपत्र दस्तावेज़ अपलोड हुआ", ck_id: "प्रमाणपत्र आईडी मौजूद", ck_name: "प्रमाणपत्र का नाम दर्ज",
  ck_org: "जारी करने वाली संस्था दर्ज", ck_issue: "जारी तिथि दर्ज", ck_expiry: "समाप्ति तिथि दर्ज",
  ck_notExpired: "प्रमाणपत्र समाप्त नहीं हुआ", ck_external: "बाहरी लाइसेंसिंग प्राधिकरण सत्यापन",
  ckExternalNote: "इस प्रोटोटाइप में बाहरी प्राधिकरण सत्यापन जुड़ा नहीं है।",
  markVerified: "सत्यापित चिह्नित करें", requestReview: "समीक्षा का अनुरोध", reject: "अस्वीकार करें",
  onlyReviewer: "केवल समीक्षक की कार्रवाई यह स्थिति बदलती है। फ़ाइल अपलोड करना या फ़ील्ड भरना डॉक्टर को सत्यापित नहीं करता।",
  verifiedOn: "सत्यापन तिथि", reviewer: "समीक्षक", reviewerName: "डेमो समीक्षक", credExpiry: "क्रेडेंशियल समाप्ति",
  verifiedNote: "केवल डेमो सत्यापन। डॉक्टर के वास्तविक क्रेडेंशियल UAE DoH या किसी लाइसेंसिंग प्राधिकरण से नहीं जांचे गए।",
  historyTitle: "सत्यापन इतिहास और ऑडिट ट्रेल",
  ev_created: "सिंथेटिक डेमो रिकॉर्ड बनाया गया", ev_added: "इस सत्र में डॉक्टर जोड़ा गया", ev_submitted: "सत्यापन के लिए भेजा गया",
  ev_uploaded: "प्रमाणपत्र अपलोड हुआ: {f}", ev_edited: "समीक्षक ने प्रमाणपत्र विवरण दर्ज या सुधारे",
  ev_verify: "समीक्षक ने सत्यापित चिह्नित किया (डेमो)", ev_request: "समीक्षक ने आगे समीक्षा का अनुरोध किया", ev_reject: "समीक्षक ने आवेदन अस्वीकार किया",
  disclaimer: "इस प्रोटोटाइप में किसी बाहरी लाइसेंसिंग प्राधिकरण से क्रेडेंशियल सत्यापन नहीं किया जाता। वास्तविक तैनाती में समीक्षकों को प्रमाणित किया जाएगा और संबंधित लाइसेंसिंग प्राधिकरण से क्रेडेंशियल सत्यापित किए जाएंगे।",
  orgFamily: "डेमो फैमिली मेडिसिन बोर्ड", orgEndo: "डेमो एंडोक्राइनोलॉजी बोर्ड",
  openReview: "प्रमाणपत्र समीक्षा खोलें", closeReview: "प्रमाणपत्र समीक्षा बंद करें",
};

const ur: CredText = {
  lblCertName: "سرٹیفکیٹ کا نام", lblCertId: "سرٹیفکیٹ آئی ڈی", lblCertOrg: "سرٹیفکیٹ جاری کرنے والا ادارہ",
  lblCertIssue: "سرٹیفکیٹ جاری ہونے کی تاریخ", lblCertExpiry: "سرٹیفکیٹ کی میعاد ختم ہونے کی تاریخ", lblUpload: "سرٹیفکیٹ اپ لوڈ کریں (اختیاری)",
  submit: "تصدیق کے لیے بھیجیں",
  st_not_verified: "غیر تصدیق شدہ", st_pending: "جائزہ زیرِ التوا", st_verified: "✓ تصدیق شدہ", st_rejected: "مسترد",
  demoVerif: "ڈیمو تصدیق",
  reviewTitle: "سرٹیفکیٹ کا جائزہ", noDoc: "کوئی سرٹیفکیٹ اپ لوڈ نہیں ہوا۔", openDoc: "دستاویز کھولیں",
  manualNote: "اس پروٹوٹائپ میں متن نکالنا دستیاب نہیں۔ جائزہ کار نیچے سرٹیفکیٹ کی تفصیلات درج یا درست کرتا ہے۔ پروٹوٹائپ ڈیٹا۔",
  saveDetails: "تفصیلات محفوظ کریں",
  checklistTitle: "تصدیقی فہرست",
  ck_doc: "سرٹیفکیٹ دستاویز اپ لوڈ ہوئی", ck_id: "سرٹیفکیٹ آئی ڈی موجود", ck_name: "سرٹیفکیٹ کا نام درج",
  ck_org: "جاری کرنے والا ادارہ درج", ck_issue: "اجرا کی تاریخ درج", ck_expiry: "میعاد ختم ہونے کی تاریخ درج",
  ck_notExpired: "سرٹیفکیٹ کی میعاد ختم نہیں ہوئی", ck_external: "بیرونی لائسنسنگ اتھارٹی سے تصدیق",
  ckExternalNote: "اس پروٹوٹائپ میں بیرونی اتھارٹی سے تصدیق منسلک نہیں ہے۔",
  markVerified: "تصدیق شدہ نشان لگائیں", requestReview: "جائزے کی درخواست", reject: "مسترد کریں",
  onlyReviewer: "صرف جائزہ کار کا عمل یہ حیثیت بدلتا ہے۔ فائل اپ لوڈ کرنا یا خانے پُر کرنا ڈاکٹر کی تصدیق نہیں کرتا۔",
  verifiedOn: "تصدیق کی تاریخ", reviewer: "جائزہ کار", reviewerName: "ڈیمو جائزہ کار", credExpiry: "اسناد کی میعاد",
  verifiedNote: "صرف ڈیمو تصدیق۔ ڈاکٹر کی حقیقی اسناد UAE DoH یا کسی لائسنسنگ اتھارٹی سے نہیں جانچی گئیں۔",
  historyTitle: "تصدیق کی تاریخچہ اور آڈٹ ٹریل",
  ev_created: "مصنوعی ڈیمو ریکارڈ بنایا گیا", ev_added: "اس سیشن میں ڈاکٹر شامل کیا گیا", ev_submitted: "تصدیق کے لیے بھیجا گیا",
  ev_uploaded: "سرٹیفکیٹ اپ لوڈ ہوا: {f}", ev_edited: "جائزہ کار نے سرٹیفکیٹ کی تفصیلات درج یا درست کیں",
  ev_verify: "جائزہ کار نے تصدیق شدہ نشان لگایا (ڈیمو)", ev_request: "جائزہ کار نے مزید جائزے کی درخواست کی", ev_reject: "جائزہ کار نے درخواست مسترد کی",
  disclaimer: "اس پروٹوٹائپ میں کسی بیرونی لائسنسنگ اتھارٹی سے اسناد کی تصدیق نہیں کی جاتی۔ حقیقی نظام میں جائزہ کاروں کی شناخت کی تصدیق ہوگی اور متعلقہ لائسنسنگ اتھارٹی سے اسناد کی تصدیق کی جائے گی۔",
  orgFamily: "ڈیمو فیملی میڈیسن بورڈ", orgEndo: "ڈیمو اینڈوکرائنولوجی بورڈ",
  openReview: "سرٹیفکیٹ کا جائزہ کھولیں", closeReview: "سرٹیفکیٹ کا جائزہ بند کریں",
};

const tl: CredText = {
  lblCertName: "Pangalan ng sertipikasyon", lblCertId: "Certificate ID", lblCertOrg: "Organisasyong nag-isyu ng sertipiko",
  lblCertIssue: "Petsa ng pag-isyu ng sertipiko", lblCertExpiry: "Petsa ng pag-expire ng sertipiko", lblUpload: "I-upload ang sertipiko (opsyonal)",
  submit: "Isumite para sa beripikasyon",
  st_not_verified: "HINDI VERIFIED", st_pending: "NAGHIHINTAY NG REVIEW", st_verified: "✓ VERIFIED", st_rejected: "TINANGGIHAN",
  demoVerif: "DEMO NA BERIPIKASYON",
  reviewTitle: "Review ng sertipiko", noDoc: "Walang na-upload na sertipiko.", openDoc: "Buksan ang dokumento",
  manualNote: "Walang text extraction sa prototype na ito. Ang reviewer ang maglalagay o magtatama ng detalye sa ibaba. Prototype na datos.",
  saveDetails: "I-save ang detalye",
  checklistTitle: "Checklist ng beripikasyon",
  ck_doc: "Na-upload ang dokumento ng sertipiko", ck_id: "May Certificate ID", ck_name: "Naitala ang pangalan ng sertipikasyon",
  ck_org: "Naitala ang nag-isyung organisasyon", ck_issue: "Naitala ang petsa ng pag-isyu", ck_expiry: "Naitala ang petsa ng pag-expire",
  ck_notExpired: "Hindi pa expired ang sertipiko", ck_external: "Beripikasyon ng panlabas na licensing authority",
  ckExternalNote: "HINDI nakakonekta ang beripikasyon ng panlabas na awtoridad sa prototype na ito.",
  markVerified: "Markahan bilang verified", requestReview: "Humiling ng review", reject: "Tanggihan",
  onlyReviewer: "Aksyon lang ng reviewer ang nagbabago ng status na ito. Hindi nave-verify ang doktor sa pag-upload o pagpuno ng fields.",
  verifiedOn: "Petsa ng beripikasyon", reviewer: "Reviewer", reviewerName: "Demo reviewer", credExpiry: "Pag-expire ng kredensyal",
  verifiedNote: "Demo na beripikasyon lang. Hindi sinuri ang tunay na kredensyal ng doktor sa UAE DoH o anumang licensing authority.",
  historyTitle: "Kasaysayan ng beripikasyon at audit trail",
  ev_created: "Nilikha ang synthetic na demo record", ev_added: "Idinagdag ang doktor sa session na ito", ev_submitted: "Isinumite para sa beripikasyon",
  ev_uploaded: "Na-upload ang sertipiko: {f}", ev_edited: "Inilagay o itinama ng reviewer ang detalye ng sertipiko",
  ev_verify: "Minarkahan ng reviewer bilang verified (demo)", ev_request: "Humiling ang reviewer ng karagdagang review", ev_reject: "Tinanggihan ng reviewer ang pagsusumite",
  disclaimer: "Hindi isinasagawa ang beripikasyon ng kredensyal sa isang panlabas na licensing authority sa prototype na ito. Sa tunay na deployment, ia-authenticate ang mga reviewer at ive-verify ang kredensyal sa kaukulang licensing authority.",
  orgFamily: "Demo Board ng Family Medicine", orgEndo: "Demo Board ng Endocrinology",
  openReview: "Buksan ang review ng sertipiko", closeReview: "Isara ang review ng sertipiko",
};

const ml: CredText = {
  lblCertName: "സർട്ടിഫിക്കേഷന്റെ പേര്", lblCertId: "സർട്ടിഫിക്കറ്റ് ഐഡി", lblCertOrg: "സർട്ടിഫിക്കറ്റ് നൽകിയ സ്ഥാപനം",
  lblCertIssue: "സർട്ടിഫിക്കറ്റ് നൽകിയ തീയതി", lblCertExpiry: "സർട്ടിഫിക്കറ്റ് കാലാവധി തീരുന്ന തീയതി", lblUpload: "സർട്ടിഫിക്കറ്റ് അപ്‌ലോഡ് ചെയ്യുക (ഐച്ഛികം)",
  submit: "പരിശോധനയ്ക്ക് സമർപ്പിക്കുക",
  st_not_verified: "സ്ഥിരീകരിച്ചിട്ടില്ല", st_pending: "അവലോകനം ബാക്കി", st_verified: "✓ സ്ഥിരീകരിച്ചു", st_rejected: "നിരസിച്ചു",
  demoVerif: "ഡെമോ സ്ഥിരീകരണം",
  reviewTitle: "സർട്ടിഫിക്കറ്റ് അവലോകനം", noDoc: "സർട്ടിഫിക്കറ്റ് അപ്‌ലോഡ് ചെയ്തിട്ടില്ല.", openDoc: "രേഖ തുറക്കുക",
  manualNote: "ഈ പ്രോട്ടോടൈപ്പിൽ ടെക്സ്റ്റ് എടുക്കൽ ലഭ്യമല്ല. അവലോകകൻ താഴെ സർട്ടിഫിക്കറ്റ് വിവരങ്ങൾ നൽകുകയോ തിരുത്തുകയോ ചെയ്യുന്നു. പ്രോട്ടോടൈപ്പ് ഡാറ്റ.",
  saveDetails: "വിവരങ്ങൾ സേവ് ചെയ്യുക",
  checklistTitle: "പരിശോധനാ ചെക്ക്‌ലിസ്റ്റ്",
  ck_doc: "സർട്ടിഫിക്കറ്റ് രേഖ അപ്‌ലോഡ് ചെയ്തു", ck_id: "സർട്ടിഫിക്കറ്റ് ഐഡി ഉണ്ട്", ck_name: "സർട്ടിഫിക്കേഷന്റെ പേര് രേഖപ്പെടുത്തി",
  ck_org: "നൽകിയ സ്ഥാപനം രേഖപ്പെടുത്തി", ck_issue: "നൽകിയ തീയതി രേഖപ്പെടുത്തി", ck_expiry: "കാലാവധി തീയതി രേഖപ്പെടുത്തി",
  ck_notExpired: "സർട്ടിഫിക്കറ്റ് കാലഹരണപ്പെട്ടിട്ടില്ല", ck_external: "ബാഹ്യ ലൈസൻസിംഗ് അതോറിറ്റി പരിശോധന",
  ckExternalNote: "ഈ പ്രോട്ടോടൈപ്പിൽ ബാഹ്യ അതോറിറ്റി പരിശോധന ബന്ധിപ്പിച്ചിട്ടില്ല.",
  markVerified: "സ്ഥിരീകരിച്ചതായി അടയാളപ്പെടുത്തുക", requestReview: "അവലോകനം ആവശ്യപ്പെടുക", reject: "നിരസിക്കുക",
  onlyReviewer: "അവലോകകന്റെ നടപടി മാത്രമേ ഈ നില മാറ്റൂ. ഫയൽ അപ്‌ലോഡ് ചെയ്യുന്നതോ ഫീൽഡുകൾ പൂരിപ്പിക്കുന്നതോ ഡോക്ടറെ സ്ഥിരീകരിക്കില്ല.",
  verifiedOn: "സ്ഥിരീകരണ തീയതി", reviewer: "അവലോകകൻ", reviewerName: "ഡെമോ അവലോകകൻ", credExpiry: "ക്രെഡൻഷ്യൽ കാലാവധി",
  verifiedNote: "ഡെമോ സ്ഥിരീകരണം മാത്രം. ഡോക്ടറുടെ യഥാർത്ഥ ക്രെഡൻഷ്യലുകൾ UAE DoH-ലോ മറ്റേതെങ്കിലും ലൈസൻസിംഗ് അതോറിറ്റിയിലോ പരിശോധിച്ചിട്ടില്ല.",
  historyTitle: "പരിശോധനാ ചരിത്രവും ഓഡിറ്റ് ട്രെയിലും",
  ev_created: "സിന്തറ്റിക് ഡെമോ റെക്കോർഡ് സൃഷ്ടിച്ചു", ev_added: "ഈ സെഷനിൽ ഡോക്ടറെ ചേർത്തു", ev_submitted: "പരിശോധനയ്ക്ക് സമർപ്പിച്ചു",
  ev_uploaded: "സർട്ടിഫിക്കറ്റ് അപ്‌ലോഡ് ചെയ്തു: {f}", ev_edited: "അവലോകകൻ സർട്ടിഫിക്കറ്റ് വിവരങ്ങൾ നൽകി അല്ലെങ്കിൽ തിരുത്തി",
  ev_verify: "അവലോകകൻ സ്ഥിരീകരിച്ചതായി അടയാളപ്പെടുത്തി (ഡെമോ)", ev_request: "അവലോകകൻ കൂടുതൽ അവലോകനം ആവശ്യപ്പെട്ടു", ev_reject: "അവലോകകൻ സമർപ്പണം നിരസിച്ചു",
  disclaimer: "ഈ പ്രോട്ടോടൈപ്പിൽ ബാഹ്യ ലൈസൻസിംഗ് അതോറിറ്റിയുമായി ക്രെഡൻഷ്യൽ പരിശോധന നടത്തുന്നില്ല. യഥാർത്ഥ വിന്യാസത്തിൽ അവലോകകരെ ആധികാരികമാക്കുകയും ബന്ധപ്പെട്ട ലൈസൻസിംഗ് അതോറിറ്റിയുമായി ക്രെഡൻഷ്യലുകൾ പരിശോധിക്കുകയും ചെയ്യും.",
  orgFamily: "ഡെമോ ഫാമിലി മെഡിസിൻ ബോർഡ്", orgEndo: "ഡെമോ എൻഡോക്രൈനോളജി ബോർഡ്",
  openReview: "സർട്ടിഫിക്കറ്റ് അവലോകനം തുറക്കുക", closeReview: "സർട്ടിഫിക്കറ്റ് അവലോകനം അടയ്ക്കുക",
};

export const credCopy: Record<Lang, CredText> = { en, ar, hi, ur, tl, ml };
export const useCredText = () => credCopy[useLang().lang];
