import { useLang, type Lang } from "@/lib/i18n";

// Text for: day 3/7/14 simulation, review-driven worklist, care team, cohort funnel,
// audit case selector and the security section.
const en = {
  demoNoticeLabel: "Presentation demo", liveNoticeLabel: "Actual deployment",
  demoLogin: "Choose a role and enter valid-looking details to open the presentation; no account is authenticated.", liveLogin: "Patients and clinicians would sign in through verified, role-based identity controls.",
  demoResult: "Change a value to demonstrate the deterministic pathway; it is not saved or sent to a clinical record.", liveResult: "Validated results would arrive from approved sources and be linked to the authenticated patient record.",
  demoReminder: "Adding or deleting a reminder changes this session only; no notification is sent.", liveReminder: "Approved reminders would be scheduled through a secure notification service with delivery records.",
  demoPatient: "Choose a fixed synthetic patient to present each pathway.", livePatient: "An authenticated patient would see only their own live case record.",
  demoTime: "Buttons compress days 3, 7 and 14 into clicks; no message is sent.", liveTime: "A scheduler would send approved reminders on the real dates and log delivery securely.",
  demoReview: "Use sample cases and reviewer actions to demonstrate the decision workflow; no clinician or health record is contacted.", liveReview: "Authorized clinicians would review assigned live cases, with decisions stored in a durable audit record.",
  demoDoctor: "Choose a fictional doctor to present the clinician views; adding a doctor lasts only for this session.", liveDoctor: "Authenticated clinicians would use their own profile, and administrators would manage approved care-team records.",
  demoCredential: "Submitting, uploading, or marking credentials changes synthetic session data only.", liveCredential: "Authorized reviewers would verify identity and credentials against approved licensing sources before access is granted.",
  demoAudit: "Choose a synthetic case to present its scripted and session activity.", liveAudit: "Authorized users would see an access-controlled, tamper-evident record for the relevant real case.",
  demoEngine: "Choose one of five fixed synthetic cases and replay the rule steps; no clinical system is contacted.", liveEngine: "Validated screening data would enter the approved rules service and create a traceable next step for the correct patient.",
  simTitle: "Demo: simulate time",
  simDesc: "Move this case forward to see what happens when follow-up is not confirmed.",
  simDay: "Simulate day {n}",
  simReset: "Reset",
  simCurrent: "Simulated day: {n}",
  simStopped: "Follow-up confirmed — reminders stopped.",
  simEscalated: "Day 14 without confirmation: your care team has been asked to review.",
  notifReminder: "Follow-up reminder",
  notifReminderDesc: "Day {n}: please confirm your health follow-up.",
  auditReminder: "Reminder sent (simulated day {n})",
  auditEscalated: "No confirmation by day 14, escalated",
  auditQuestionSent: "Question routed to the care team (text is not stored in the audit trail)",
  askEid: "Please don't include an Emirates ID in your question.",
  reasonNoHistory: "Prior screening history missing",
  reasonMedication: "Medication context unclear",
  reasonDay14: "No confirmation by day 14, escalated",
  nextStepHeader: "Next step",
  nsReview: "Reviewer: Confirm / Adjust / Escalate the pathway",
  nsDay14: "Reviewer contacts the patient: Confirm / Adjust / Escalate",
  worklistEmpty: "No cases need review right now.",
  lblResult: "Result",
  lblHistory: "Prior screening history",
  lblMedicine: "Medicine on record",
  lblRules: "Rules applied",
  lblReminders: "Reminders",
  remindersNoReply: "Day 3 and day 7 sent, no confirmation",
  yes: "Yes", no: "No", none: "None",
  medCheck: "Medication context",
  medCheckD: "A medicine is on record. The system does not know why it was prescribed; the result band is not changed.",
  routedMed: "Routed to a human reviewer (RULE-004)",
  routedMedD: "The reason for the medicine is not known, so a person must check the pathway before anything is sent.",
  engWaitD5: "Waiting for review — reminders start only after a reviewer confirms.",
  engWaitD6: "Waiting for review: routed to a human reviewer ({rule}).",
  engReferralD4: "Referral: follow-up is set by the clinician after the assessment. No 3/6/12-month schedule.",
  careTeamTitle: "Care team (demo)",
  careTeamDesc: "Fictional doctors for this prototype. All credentials shown are synthetic demo data.",
  lblSpecialty: "Specialty",
  lblHospital: "Hospital",
  specFamily: "Family medicine",
  specEndo: "Endocrinology",
  hospA: "Demo Family Health Centre — Jumeirah",
  hospB: "Demo Primary Care Clinic — Deira",
  credNote: "Credential verification is not performed in this prototype. A production deployment would authenticate reviewers against the relevant licensing authority before granting verified status.",
  lblRole: "Role",
  lblLicense: "Medical license number",
  lblAuthority: "Licensing authority",
  lblLicenseExpiry: "License expiry",
  lblCerts: "Certifications",
  lblCertExpiry: "Certification expiry",
  lblVerification: "Verification status",
  lblFullName: "Full name",
  roleValue: "Physician",
  authorityDoH: "UAE DoH",
  certFamily: "Family Medicine Certification",
  certEndo: "Endocrinology Certification",
  statusDemo: "DEMO — NOT VERIFIED",
  statusNotVerified: "Not verified",
  viewCreds: "View credentials",
  hideCreds: "Hide credentials",
  addDoctor: "+ Add doctor",
  saveDoctor: "Save doctor",
  cancelDoctor: "Cancel",
  errRequired: "Please fill in every field.",
  demoBadge: "Synthetic demo data",
  addedNote: "Added in this session only. Status stays Not verified; this prototype cannot verify licenses.",
  cohortLabel: "Synthetic cohort, illustrative only.",
  fScreened: "Screened", fResulted: "Resulted", fFlagged: "Flagged",
  fConfirmed: "Confirmed", fLocation: "Location chosen", fBooked: "Booked", fCompleted: "Visit completed",
  ofScreened: "{p}% of screened",
  ofFlagged: "{p}% of flagged",
  screeningFunnel: "Screening",
  followFunnel: "Follow-through among flagged people",
  attention: "Attention needed",
  aNotConfirmed: "Flagged, not confirmed",
  aNotBooked: "Confirmed, not booked",
  aNotCompleted: "Booked, visit not completed",
  caseSelect: "Case",
  caseEvents: "Case events (from the shared case data)",
  secTitle: "Security and data protection",
  secTrue: "True of this prototype",
  secT1: "Synthetic data only.",
  secT2: "No AI key in the browser.",
  secT3: "The system never diagnoses.",
  secT4: "Every decision traces to a rule ID. Clinical thresholds cite the UAE DoH standard; RULE-003 and RULE-004 are prototype safety rules.",
  secReq: "Required before real data",
  secR1: "Encryption", secR2: "Real authentication", secR3: "UAE data residency", secR4: "Tamper-evident server-side storage", secR5: "Security review", secR6: "Clinical validation", secR7: "Live connection to Malaffi, Nabidh and Riayati — the UAE's health information exchanges — for results and follow-up status.",
  secModel: "This prototype uses no AI model. A deployment could use one only to read a photographed slip into text; every decision would still come from rules.",
  tabNeeds: "Needs review",
  tabAll: "All cases",
  tabReviewed: "Reviewed",
  colReviewNeeded: "Review needed?",
  colEngineReason: "Engine's reason",
  colDecision: "Decision",
  colTime: "Time",
  colReviewer: "Reviewer",
  erPre: "Prediabetes range, screening history on record, no medicine: pathway sent without review.",
  erReferral: "Referral range: sent straight to a clinician assessment, no review needed.",
  erNormal: "Below the prediabetes range: no follow-up needed.",
  progAwaiting: "Awaiting reviewer",
  progConfirmed: "Reviewer confirmed",
  progAdjusted: "Reviewer adjusted",
  progEscalated: "Escalated",
  progNotEscalated: "Not escalated",
  reviewedEmpty: "No cases reviewed yet.",
  sampleNote: "Shows the five named sample cases. The population funnel is a separate synthetic cohort.",
  funnelDef: "Flagged = result in the prediabetes or referral range. Confirmed = patient accepted the follow-up plan.",
  largestLoss: "Largest funnel reduction: {from} → {to} — {n} people ({p}%) {why}.",
  lossNotFlagged: "were not flagged based on the defined thresholds",
  lossGeneric: "did not continue to the next step",
  mohap: "In MOHAP's national campaign, among people who followed the lifestyle guidance after being flagged prediabetic, 8.1% returned to a normal HbA1c within six months and 1% progressed to type 2 diabetes.",
  auditRecordedD: "{test} {value} received from the screening lab and attached to the case.",
};
type D = typeof en;
const ar: D = {
  demoNoticeLabel: "عرض تقديمي تجريبي", liveNoticeLabel: "في النشر الفعلي",
  demoLogin: "اختر دوراً وأدخل بيانات تبدو صحيحة لفتح العرض؛ لا تتم مصادقة أي حساب.", liveLogin: "يسجل المرضى والأطباء الدخول عبر ضوابط هوية موثقة ومبنية على الأدوار.",
  demoResult: "غيّر قيمة لعرض المسار الحتمي؛ لا يتم حفظها أو إرسالها إلى سجل سريري.", liveResult: "تصل النتائج المتحقق منها من مصادر معتمدة وتُربط بسجل المريض الموثّق.",
  demoReminder: "تؤثر إضافة التذكير أو حذفه في هذه الجلسة فقط؛ ولا يُرسل أي إشعار.", liveReminder: "تُجدول التذكيرات المعتمدة عبر خدمة إشعارات آمنة مع سجلات التسليم.",
  demoPatient: "اختر مريضاً اصطناعياً ثابتاً لعرض كل مسار.", livePatient: "لن يرى المريض الموثّق إلا سجل حالته الفعلي.",
  demoTime: "تختصر الأزرار الأيام 3 و7 و14 إلى نقرات؛ ولا تُرسل أي رسالة.", liveTime: "تُرسل خدمة جدولة التذكيرات المعتمدة في مواعيدها الفعلية وتُسجل التسليم بأمان.",
  demoReview: "استخدم الحالات التجريبية وإجراءات المراجع لعرض سير القرار؛ لا يتم الاتصال بطبيب أو سجل صحي.", liveReview: "يراجع الأطباء المخوّلون الحالات الفعلية المسندة إليهم، وتُحفظ القرارات في سجل تدقيق دائم.",
  demoDoctor: "اختر طبيباً خيالياً لعرض واجهات الطبيب؛ وتبقى إضافة الطبيب خلال هذه الجلسة فقط.", liveDoctor: "يستخدم الأطباء الموثّقون ملفاتهم الخاصة، ويدير المسؤولون سجلات فريق الرعاية المعتمدة.",
  demoCredential: "يغيّر الإرسال أو الرفع أو وضع حالة التحقق بيانات الجلسة الاصطناعية فقط.", liveCredential: "يتحقق المراجعون المخوّلون من الهوية والاعتمادات عبر مصادر الترخيص المعتمدة قبل منح الوصول.",
  demoAudit: "اختر حالة اصطناعية لعرض نشاطها المكتوب ونشاط هذه الجلسة.", liveAudit: "يرى المستخدمون المخوّلون سجلاً محمياً من التلاعب ومقيد الوصول للحالة الفعلية المعنية.",
  demoEngine: "اختر واحدة من خمس حالات اصطناعية ثابتة وأعد تشغيل خطوات القواعد؛ لا يتم الاتصال بأي نظام سريري.", liveEngine: "تدخل بيانات الفحص المتحقق منها إلى خدمة القواعد المعتمدة لإنشاء خطوة تالية قابلة للتتبع للمريض الصحيح.",
  simTitle: "تجريبي: محاكاة الوقت",
  simDesc: "حرّك هذه الحالة للأمام لترى ما يحدث عند عدم تأكيد المتابعة.",
  simDay: "محاكاة اليوم {n}",
  simReset: "إعادة ضبط",
  simCurrent: "اليوم المحاكى: {n}",
  simStopped: "تم تأكيد المتابعة — توقفت التذكيرات.",
  simEscalated: "اليوم 14 دون تأكيد: طُلب من فريق الرعاية المراجعة.",
  notifReminder: "تذكير بالمتابعة",
  notifReminderDesc: "اليوم {n}: يرجى تأكيد متابعتك الصحية.",
  auditReminder: "أُرسل تذكير (اليوم المحاكى {n})",
  auditEscalated: "لا تأكيد حتى اليوم 14، تم التصعيد",
  auditQuestionSent: "أُحيل السؤال إلى فريق الرعاية (لا يُحفظ النص في سجل التدقيق)",
  askEid: "يرجى عدم تضمين رقم الهوية الإماراتية في سؤالك.",
  reasonNoHistory: "سجل الفحص السابق مفقود",
  reasonMedication: "سياق الدواء غير واضح",
  reasonDay14: "لا تأكيد حتى اليوم 14، تم التصعيد",
  nextStepHeader: "الخطوة التالية",
  nsReview: "المراجع: تأكيد / تعديل / تصعيد المسار",
  nsDay14: "يتواصل المراجع مع المريض: تأكيد / تعديل / تصعيد",
  worklistEmpty: "لا توجد حالات تحتاج مراجعة الآن.",
  lblResult: "النتيجة",
  lblHistory: "سجل الفحص السابق",
  lblMedicine: "الدواء المسجل",
  lblRules: "القواعد المطبقة",
  lblReminders: "التذكيرات",
  remindersNoReply: "أُرسل في اليوم 3 واليوم 7، دون تأكيد",
  yes: "نعم", no: "لا", none: "لا يوجد",
  medCheck: "سياق الدواء",
  medCheckD: "يوجد دواء مسجل. لا يعرف النظام سبب وصفه؛ لا يتغير تصنيف النتيجة.",
  routedMed: "أُحيلت إلى مراجع بشري (RULE-004)",
  routedMedD: "سبب الدواء غير معروف، لذا يجب أن يتحقق شخص من المسار قبل إرسال أي شيء.",
  engWaitD5: "بانتظار المراجعة — تبدأ التذكيرات فقط بعد تأكيد المراجع.",
  engWaitD6: "بانتظار المراجعة: أُحيلت إلى مراجع بشري ({rule}).",
  engReferralD4: "إحالة: يحدد الطبيب المتابعة بعد التقييم. لا جدول 3/6/12 شهراً.",
  careTeamTitle: "فريق الرعاية (تجريبي)",
  careTeamDesc: "أطباء خياليون لهذا النموذج. جميع الاعتمادات المعروضة بيانات تجريبية.",
  lblSpecialty: "التخصص",
  lblHospital: "المستشفى",
  specFamily: "طب الأسرة",
  specEndo: "الغدد الصماء",
  hospA: "مركز صحة الأسرة التجريبي — جميرا",
  hospB: "عيادة الرعاية الأولية التجريبية — ديرة",
  credNote: "لا يتم التحقق من الاعتمادات في هذا النموذج. في النشر الفعلي يتم التحقق من المراجعين لدى جهة الترخيص المعنية قبل منح حالة \"موثّق\".",
  lblRole: "الدور",
  lblLicense: "رقم الترخيص الطبي",
  lblAuthority: "جهة الترخيص",
  lblLicenseExpiry: "انتهاء الترخيص",
  lblCerts: "الشهادات",
  lblCertExpiry: "انتهاء الشهادة",
  lblVerification: "حالة التحقق",
  lblFullName: "الاسم الكامل",
  roleValue: "طبيب",
  authorityDoH: "دائرة الصحة – الإمارات",
  certFamily: "شهادة طب الأسرة",
  certEndo: "شهادة الغدد الصماء",
  statusDemo: "تجريبي — غير موثّق",
  statusNotVerified: "غير موثّق",
  viewCreds: "عرض الاعتمادات",
  hideCreds: "إخفاء الاعتمادات",
  addDoctor: "+ إضافة طبيب",
  saveDoctor: "حفظ الطبيب",
  cancelDoctor: "إلغاء",
  errRequired: "يرجى تعبئة جميع الحقول.",
  demoBadge: "بيانات تجريبية",
  addedNote: "أُضيف في هذه الجلسة فقط. تبقى الحالة غير موثّق؛ لا يمكن لهذا النموذج التحقق من التراخيص.",
  cohortLabel: "مجموعة تجريبية، للتوضيح فقط.",
  fScreened: "تم فحصهم", fResulted: "صدرت نتائجهم", fFlagged: "تم تمييزهم",
  fConfirmed: "أكدوا", fLocation: "اختاروا موقعاً", fBooked: "حجزوا", fCompleted: "أكملوا الزيارة",
  ofScreened: "{p}% من المفحوصين",
  ofFlagged: "{p}% من المميَّزين",
  screeningFunnel: "الفحص",
  followFunnel: "إكمال المتابعة بين المميَّزين",
  attention: "بحاجة إلى انتباه",
  aNotConfirmed: "مميَّز، لم يؤكد",
  aNotBooked: "أكد، لم يحجز",
  aNotCompleted: "حجز، لم يكمل الزيارة",
  caseSelect: "الحالة",
  caseEvents: "أحداث الحالة (من بيانات الحالات المشتركة)",
  secTitle: "الأمن وحماية البيانات",
  secTrue: "صحيح في هذا النموذج",
  secT1: "بيانات تجريبية فقط.",
  secT2: "لا يوجد مفتاح ذكاء اصطناعي في المتصفح.",
  secT3: "النظام لا يشخّص أبداً.",
  secT4: "كل قرار يرتبط برقم قاعدة. تستند الحدود السريرية إلى معيار دائرة الصحة في الإمارات؛ RULE-003 وRULE-004 قواعد سلامة خاصة بالنموذج.",
  secReq: "مطلوب قبل استخدام بيانات حقيقية",
  secR1: "التشفير", secR2: "مصادقة حقيقية", secR3: "إقامة البيانات في الإمارات", secR4: "تخزين على الخادم مقاوم للعبث", secR5: "مراجعة أمنية", secR6: "تحقق سريري", secR7: "اتصال فعلي بمنصات Malaffi (ملفّي) وNabidh (نبض) وRiayati (رياضتي) — منصات تبادل المعلومات الصحية في الإمارات — للنتائج وحالة المتابعة.",
  secModel: "لا يستخدم هذا النموذج أي نموذج ذكاء اصطناعي. يمكن للنشر الفعلي استخدامه فقط لقراءة صورة القسيمة وتحويلها إلى نص؛ وتبقى كل القرارات صادرة عن القواعد.",
  tabNeeds: "تحتاج مراجعة",
  tabAll: "كل الحالات",
  tabReviewed: "تمت مراجعتها",
  colReviewNeeded: "هل تلزم مراجعة؟",
  colEngineReason: "سبب المحرك",
  colDecision: "القرار",
  colTime: "الوقت",
  colReviewer: "المراجع",
  erPre: "ضمن نطاق ما قبل السكري، سجل الفحص موجود، لا دواء: أُرسل المسار دون مراجعة.",
  erReferral: "ضمن نطاق الإحالة: أُرسلت مباشرة لتقييم الطبيب، لا حاجة لمراجعة.",
  erNormal: "أقل من نطاق ما قبل السكري: لا حاجة للمتابعة.",
  progAwaiting: "بانتظار المراجع",
  progConfirmed: "أكّد المراجع",
  progAdjusted: "عدّل المراجع",
  progEscalated: "تم التصعيد",
  progNotEscalated: "لم تُصعَّد",
  reviewedEmpty: "لم تتم مراجعة أي حالة بعد.",
  sampleNote: "يعرض الحالات التجريبية الخمس المسماة. قمع السكان مجموعة تجريبية منفصلة.",
  funnelDef: "المميَّزون = نتيجة ضمن نطاق ما قبل السكري أو الإحالة. المؤكِّدون = مريض قبل خطة المتابعة.",
  largestLoss: "أكبر انخفاض في المسار: {from} ← {to} — {n} شخصاً ({p}%) {why}.",
  lossNotFlagged: "لم تُرصد وفق الحدود المحددة",
  lossGeneric: "لم يكملوا إلى الخطوة التالية",
  mohap: "في الحملة الوطنية لوزارة الصحة ووقاية المجتمع، بين من اتبعوا إرشادات نمط الحياة بعد تصنيفهم في مرحلة ما قبل السكري، عاد 8.1% إلى مستوى HbA1c طبيعي خلال ستة أشهر وتطور 1% إلى السكري من النوع الثاني.",
  auditRecordedD: "تم استلام {test} {value} من مختبر الفحص وإرفاقه بالحالة.",
};
const hi: D = {
  demoNoticeLabel: "प्रस्तुति डेमो", liveNoticeLabel: "वास्तविक तैनाती",
  demoLogin: "प्रस्तुति खोलने के लिए भूमिका चुनें और मान्य-जैसी जानकारी डालें; कोई खाता प्रमाणित नहीं होता।", liveLogin: "मरीज़ और चिकित्सक प्रमाणित, भूमिका-आधारित पहचान नियंत्रण से साइन इन करेंगे।",
  demoResult: "तय पाथवे दिखाने के लिए मान बदलें; यह किसी क्लिनिकल रिकॉर्ड में सहेजा या भेजा नहीं जाता।", liveResult: "मान्य परिणाम स्वीकृत स्रोतों से आएँगे और प्रमाणित मरीज़ रिकॉर्ड से जुड़ेंगे।",
  demoReminder: "रिमाइंडर जोड़ना या हटाना केवल इस सत्र को बदलता है; कोई सूचना नहीं भेजी जाती।", liveReminder: "स्वीकृत रिमाइंडर सुरक्षित सूचना सेवा से शेड्यूल होंगे और डिलीवरी रिकॉर्ड रखे जाएँगे।",
  demoPatient: "हर पाथवे दिखाने के लिए एक तय कृत्रिम मरीज़ चुनें।", livePatient: "प्रमाणित मरीज़ केवल अपना वास्तविक केस रिकॉर्ड देखेगा।",
  demoTime: "बटन दिन 3, 7 और 14 को क्लिक में दिखाते हैं; कोई संदेश नहीं भेजा जाता।", liveTime: "शेड्यूलर सही तारीखों पर स्वीकृत रिमाइंडर भेजेगा और डिलीवरी सुरक्षित रूप से दर्ज करेगा।",
  demoReview: "निर्णय प्रक्रिया दिखाने के लिए नमूना केस और समीक्षक कार्रवाई उपयोग करें; किसी चिकित्सक या स्वास्थ्य रिकॉर्ड से संपर्क नहीं होता।", liveReview: "अधिकृत चिकित्सक सौंपे गए वास्तविक केस देखेंगे और निर्णय स्थायी ऑडिट रिकॉर्ड में सुरक्षित होंगे।",
  demoDoctor: "चिकित्सक स्क्रीन दिखाने के लिए काल्पनिक डॉक्टर चुनें; जोड़ा गया डॉक्टर केवल इस सत्र तक रहता है।", liveDoctor: "प्रमाणित चिकित्सक अपनी प्रोफ़ाइल उपयोग करेंगे और प्रशासक स्वीकृत देखभाल-टीम रिकॉर्ड संभालेंगे।",
  demoCredential: "जमा करना, अपलोड करना या स्थिति बदलना केवल कृत्रिम सत्र डेटा बदलता है।", liveCredential: "अधिकृत समीक्षक पहुँच देने से पहले स्वीकृत लाइसेंसिंग स्रोतों से पहचान और क्रेडेंशियल जाँचेंगे।",
  demoAudit: "लिखित और सत्र गतिविधि दिखाने के लिए कृत्रिम केस चुनें।", liveAudit: "अधिकृत उपयोगकर्ता संबंधित वास्तविक केस का नियंत्रित, छेड़छाड़-स्पष्ट रिकॉर्ड देखेंगे।",
  demoEngine: "पाँच तय कृत्रिम केस में से एक चुनकर नियम चरण दोहराएँ; किसी क्लिनिकल सिस्टम से संपर्क नहीं होता।", liveEngine: "मान्य स्क्रीनिंग डेटा स्वीकृत नियम सेवा में जाकर सही मरीज़ के लिए पता लगाने योग्य अगला कदम बनाएगा।",
  simTitle: "डेमो: समय का अनुकरण",
  simDesc: "यह केस आगे बढ़ाएँ और देखें कि फ़ॉलो-अप पक्का न होने पर क्या होता है।",
  simDay: "दिन {n} का अनुकरण",
  simReset: "रीसेट",
  simCurrent: "अनुकरणित दिन: {n}",
  simStopped: "फ़ॉलो-अप पक्का — रिमाइंडर बंद।",
  simEscalated: "दिन 14 तक पुष्टि नहीं: देखभाल टीम से समीक्षा के लिए कहा गया।",
  notifReminder: "फ़ॉलो-अप रिमाइंडर",
  notifReminderDesc: "दिन {n}: कृपया अपने स्वास्थ्य फ़ॉलो-अप की पुष्टि करें।",
  auditReminder: "रिमाइंडर भेजा गया (अनुकरणित दिन {n})",
  auditEscalated: "दिन 14 तक पुष्टि नहीं, आगे बढ़ाया गया",
  auditQuestionSent: "प्रश्न देखभाल टीम को भेजा गया (टेक्स्ट ऑडिट ट्रेल में नहीं रखा जाता)",
  askEid: "कृपया अपने प्रश्न में एमिरेट्स आईडी न लिखें।",
  reasonNoHistory: "पिछला स्क्रीनिंग इतिहास नहीं है",
  reasonMedication: "दवा का संदर्भ स्पष्ट नहीं",
  reasonDay14: "दिन 14 तक पुष्टि नहीं, आगे बढ़ाया गया",
  nextStepHeader: "अगला कदम",
  nsReview: "समीक्षक: पाथवे की पुष्टि / बदलाव / एस्केलेट",
  nsDay14: "समीक्षक मरीज़ से संपर्क करें: पुष्टि / बदलाव / एस्केलेट",
  worklistEmpty: "अभी किसी केस को समीक्षा की ज़रूरत नहीं।",
  lblResult: "परिणाम",
  lblHistory: "पिछला स्क्रीनिंग इतिहास",
  lblMedicine: "दर्ज दवा",
  lblRules: "लागू नियम",
  lblReminders: "रिमाइंडर",
  remindersNoReply: "दिन 3 और 7 को भेजे, कोई पुष्टि नहीं",
  yes: "हाँ", no: "नहीं", none: "कोई नहीं",
  medCheck: "दवा का संदर्भ",
  medCheckD: "एक दवा दर्ज है। सिस्टम नहीं जानता कि यह क्यों लिखी गई; परिणाम की श्रेणी नहीं बदली जाती।",
  routedMed: "मानव समीक्षक को भेजा गया (RULE-004)",
  routedMedD: "दवा का कारण ज्ञात नहीं है, इसलिए कुछ भी भेजने से पहले किसी व्यक्ति को मार्ग जाँचना होगा।",
  engWaitD5: "समीक्षा की प्रतीक्षा — समीक्षक की पुष्टि के बाद ही रिमाइंडर शुरू होंगे।",
  engWaitD6: "समीक्षा की प्रतीक्षा: मानव समीक्षक को भेजा गया ({rule})।",
  engReferralD4: "रेफ़रल: मूल्यांकन के बाद फ़ॉलो-अप डॉक्टर तय करेंगे। 3/6/12 महीने का शेड्यूल नहीं।",
  careTeamTitle: "देखभाल टीम (डेमो)",
  careTeamDesc: "इस प्रोटोटाइप के काल्पनिक डॉक्टर। दिखाए गए सभी प्रमाण-पत्र कृत्रिम डेमो डेटा हैं।",
  lblSpecialty: "विशेषज्ञता",
  lblHospital: "अस्पताल",
  specFamily: "फ़ैमिली मेडिसिन",
  specEndo: "एंडोक्रिनोलॉजी",
  hospA: "डेमो फ़ैमिली हेल्थ सेंटर — जुमेराह",
  hospB: "डेमो प्राइमरी केयर क्लिनिक — देइरा",
  credNote: "इस प्रोटोटाइप में प्रमाण-पत्रों का सत्यापन नहीं होता। वास्तविक उपयोग में सत्यापित स्थिति देने से पहले समीक्षकों को संबंधित लाइसेंसिंग प्राधिकरण से प्रमाणित किया जाएगा।",
  lblRole: "भूमिका",
  lblLicense: "मेडिकल लाइसेंस नंबर",
  lblAuthority: "लाइसेंसिंग प्राधिकरण",
  lblLicenseExpiry: "लाइसेंस समाप्ति",
  lblCerts: "प्रमाणपत्र",
  lblCertExpiry: "प्रमाणपत्र समाप्ति",
  lblVerification: "सत्यापन स्थिति",
  lblFullName: "पूरा नाम",
  roleValue: "चिकित्सक",
  authorityDoH: "UAE DoH",
  certFamily: "फ़ैमिली मेडिसिन प्रमाणपत्र",
  certEndo: "एंडोक्रिनोलॉजी प्रमाणपत्र",
  statusDemo: "डेमो — सत्यापित नहीं",
  statusNotVerified: "सत्यापित नहीं",
  viewCreds: "प्रमाण-पत्र देखें",
  hideCreds: "प्रमाण-पत्र छिपाएँ",
  addDoctor: "+ डॉक्टर जोड़ें",
  saveDoctor: "डॉक्टर सहेजें",
  cancelDoctor: "रद्द करें",
  errRequired: "कृपया हर फ़ील्ड भरें।",
  demoBadge: "कृत्रिम डेमो डेटा",
  addedNote: "केवल इस सत्र में जोड़ा गया। स्थिति 'सत्यापित नहीं' रहती है; यह प्रोटोटाइप लाइसेंस सत्यापित नहीं कर सकता।",
  cohortLabel: "कृत्रिम समूह, केवल उदाहरण के लिए।",
  fScreened: "स्क्रीन किए गए", fResulted: "परिणाम मिले", fFlagged: "चिह्नित",
  fConfirmed: "पुष्टि की", fLocation: "स्थान चुना", fBooked: "बुक किया", fCompleted: "विज़िट पूरी",
  ofScreened: "स्क्रीन किए गए का {p}%",
  ofFlagged: "चिह्नित का {p}%",
  screeningFunnel: "स्क्रीनिंग",
  followFunnel: "चिह्नित लोगों में फ़ॉलो-थ्रू",
  attention: "ध्यान चाहिए",
  aNotConfirmed: "चिह्नित, पुष्टि नहीं",
  aNotBooked: "पुष्टि की, बुक नहीं",
  aNotCompleted: "बुक किया, विज़िट पूरी नहीं",
  caseSelect: "केस",
  caseEvents: "केस घटनाएँ (साझा केस डेटा से)",
  secTitle: "सुरक्षा और डेटा संरक्षण",
  secTrue: "इस प्रोटोटाइप के बारे में सच",
  secT1: "केवल कृत्रिम डेटा।",
  secT2: "ब्राउज़र में कोई AI कुंजी नहीं।",
  secT3: "सिस्टम कभी निदान नहीं करता।",
  secT4: "हर निर्णय एक नियम ID से जुड़ा है। क्लिनिकल सीमाएँ UAE DoH मानक का हवाला देती हैं; RULE-003 और RULE-004 प्रोटोटाइप के सुरक्षा नियम हैं।",
  secReq: "वास्तविक डेटा से पहले ज़रूरी",
  secR1: "एन्क्रिप्शन", secR2: "वास्तविक प्रमाणीकरण", secR3: "UAE डेटा रेज़िडेंसी", secR4: "छेड़छाड़-प्रमाण सर्वर स्टोरेज", secR5: "सुरक्षा समीक्षा", secR6: "क्लिनिकल सत्यापन", secR7: "परिणामों और फ़ॉलो-अप स्थिति के लिए Malaffi, Nabidh और Riayati — यूएई के हेल्थ इन्फॉर्मेशन एक्सचेंज — से सीधा कनेक्शन।",
  secModel: "यह प्रोटोटाइप कोई AI मॉडल उपयोग नहीं करता। वास्तविक उपयोग में इसे केवल फ़ोटो खींची पर्ची को टेक्स्ट में पढ़ने के लिए लगाया जा सकता है; हर निर्णय फिर भी नियमों से ही होगा।",
  tabNeeds: "समीक्षा आवश्यक",
  tabAll: "सभी केस",
  tabReviewed: "समीक्षित",
  colReviewNeeded: "समीक्षा चाहिए?",
  colEngineReason: "इंजन का कारण",
  colDecision: "निर्णय",
  colTime: "समय",
  colReviewer: "समीक्षक",
  erPre: "प्रीडायबिटीज़ सीमा, स्क्रीनिंग इतिहास दर्ज, कोई दवा नहीं: मार्ग बिना समीक्षा भेजा गया।",
  erReferral: "रेफ़रल सीमा: सीधे चिकित्सक के मूल्यांकन के लिए भेजा गया, समीक्षा की ज़रूरत नहीं।",
  erNormal: "प्रीडायबिटीज़ सीमा से नीचे: फ़ॉलो-अप की ज़रूरत नहीं।",
  progAwaiting: "समीक्षक की प्रतीक्षा",
  progConfirmed: "समीक्षक ने पुष्टि की",
  progAdjusted: "समीक्षक ने बदला",
  progEscalated: "आगे बढ़ाया गया",
  progNotEscalated: "आगे नहीं बढ़ाया गया",
  reviewedEmpty: "अभी तक किसी केस की समीक्षा नहीं हुई।",
  sampleNote: "पाँच नामित नमूना केस दिखाता है। जनसंख्या फ़नल एक अलग कृत्रिम समूह है।",
  funnelDef: "चिह्नित = परिणाम प्रीडायबिटीज़ या रेफ़रल सीमा में। पुष्टि = मरीज़ ने फ़ॉलो-अप योजना स्वीकार की।",
  largestLoss: "सबसे बड़ी फ़नल कमी: {from} → {to} — {n} लोग ({p}%) {why}.",
  lossNotFlagged: "परिभाषित सीमाओं के आधार पर ध्वजांकित नहीं हुए",
  lossGeneric: "अगले चरण तक नहीं पहुँचे",
  mohap: "MOHAP के राष्ट्रीय अभियान में, प्रीडायबिटिक चिह्नित होने के बाद जीवनशैली मार्गदर्शन अपनाने वालों में से 8.1% छह महीनों में सामान्य HbA1c पर लौटे और 1% टाइप 2 डायबिटीज़ तक पहुँचे।",
  auditRecordedD: "{test} {value} स्क्रीनिंग लैब से मिला और केस से जोड़ा गया।",
};
const ur: D = {
  demoNoticeLabel: "پریزنٹیشن ڈیمو", liveNoticeLabel: "حقیقی نفاذ",
  demoLogin: "پریزنٹیشن کھولنے کے لیے کردار منتخب کریں اور درست نظر آنے والی معلومات درج کریں؛ کسی اکاؤنٹ کی تصدیق نہیں ہوتی۔", liveLogin: "مریض اور معالج تصدیق شدہ، کردار پر مبنی شناختی نظام سے سائن ان کریں گے۔",
  demoResult: "طے شدہ راستہ دکھانے کے لیے قدر بدلیں؛ یہ کسی طبی ریکارڈ میں محفوظ یا بھیجی نہیں جاتی۔", liveResult: "تصدیق شدہ نتائج منظور شدہ ذرائع سے آئیں گے اور تصدیق شدہ مریض ریکارڈ سے منسلک ہوں گے۔",
  demoReminder: "یاد دہانی شامل یا حذف کرنا صرف اس سیشن کو بدلتا ہے؛ کوئی اطلاع نہیں بھیجی جاتی۔", liveReminder: "منظور شدہ یاد دہانیاں محفوظ نوٹیفکیشن سروس کے ذریعے شیڈول ہوں گی اور ترسیل کا ریکارڈ رکھا جائے گا۔",
  demoPatient: "ہر راستہ دکھانے کے لیے ایک مقررہ مصنوعی مریض منتخب کریں۔", livePatient: "تصدیق شدہ مریض صرف اپنا حقیقی کیس ریکارڈ دیکھے گا۔",
  demoTime: "بٹن دن 3، 7 اور 14 کو کلکس میں دکھاتے ہیں؛ کوئی پیغام نہیں بھیجا جاتا۔", liveTime: "شیڈیولر حقیقی تاریخوں پر منظور شدہ یاد دہانیاں بھیجے گا اور ترسیل محفوظ طور پر درج کرے گا۔",
  demoReview: "فیصلے کا عمل دکھانے کے لیے نمونہ کیس اور جائزہ کار کے اقدامات استعمال کریں؛ کسی معالج یا صحت ریکارڈ سے رابطہ نہیں ہوتا۔", liveReview: "مجاز معالج تفویض شدہ حقیقی کیس دیکھیں گے اور فیصلے مستقل آڈٹ ریکارڈ میں محفوظ ہوں گے۔",
  demoDoctor: "معالج کے صفحات دکھانے کے لیے فرضی ڈاکٹر منتخب کریں؛ شامل کیا گیا ڈاکٹر صرف اس سیشن تک رہتا ہے۔", liveDoctor: "تصدیق شدہ معالج اپنی پروفائل استعمال کریں گے اور منتظم منظور شدہ نگہداشت ٹیم کے ریکارڈ سنبھالیں گے۔",
  demoCredential: "جمع کرنا، اپ لوڈ کرنا یا تصدیقی حیثیت بدلنا صرف مصنوعی سیشن ڈیٹا تبدیل کرتا ہے۔", liveCredential: "مجاز جائزہ کار رسائی دینے سے پہلے منظور شدہ لائسنسنگ ذرائع سے شناخت اور اسناد کی تصدیق کریں گے۔",
  demoAudit: "لکھے ہوئے اور سیشن کے واقعات دکھانے کے لیے مصنوعی کیس منتخب کریں۔", liveAudit: "مجاز صارف متعلقہ حقیقی کیس کا رسائی محدود اور چھیڑ چھاڑ ظاہر کرنے والا ریکارڈ دیکھیں گے۔",
  demoEngine: "پانچ مقررہ مصنوعی کیسوں میں سے ایک منتخب کر کے قواعد کے مراحل چلائیں؛ کسی طبی نظام سے رابطہ نہیں ہوتا۔", liveEngine: "تصدیق شدہ اسکریننگ ڈیٹا منظور شدہ قواعد کی سروس میں جا کر درست مریض کے لیے قابل سراغ اگلا قدم بنائے گا۔",
  simTitle: "ڈیمو: وقت کی نقل",
  simDesc: "اس کیس کو آگے بڑھائیں اور دیکھیں کہ فالو اپ کی تصدیق نہ ہونے پر کیا ہوتا ہے۔",
  simDay: "دن {n} کی نقل",
  simReset: "ری سیٹ",
  simCurrent: "نقلی دن: {n}",
  simStopped: "فالو اپ کی تصدیق — یاد دہانیاں بند۔",
  simEscalated: "دن 14 تک تصدیق نہیں: نگہداشت ٹیم سے جائزے کا کہا گیا۔",
  notifReminder: "فالو اپ یاد دہانی",
  notifReminderDesc: "دن {n}: براہ کرم اپنے صحت فالو اپ کی تصدیق کریں۔",
  auditReminder: "یاد دہانی بھیجی گئی (نقلی دن {n})",
  auditEscalated: "دن 14 تک تصدیق نہیں، آگے بڑھایا گیا",
  auditQuestionSent: "سوال نگہداشت ٹیم کو بھیجا گیا (متن آڈٹ ٹریل میں محفوظ نہیں ہوتا)",
  askEid: "براہ کرم اپنے سوال میں ایمریٹس آئی ڈی شامل نہ کریں۔",
  reasonNoHistory: "سابقہ اسکریننگ تاریخ موجود نہیں",
  reasonMedication: "دوا کا سیاق واضح نہیں",
  reasonDay14: "دن 14 تک تصدیق نہیں، آگے بڑھایا گیا",
  nextStepHeader: "اگلا قدم",
  nsReview: "جائزہ کار: راستے کی تصدیق / ترمیم / ایسکلیٹ",
  nsDay14: "جائزہ کار مریض سے رابطہ کرے: تصدیق / ترمیم / ایسکلیٹ",
  worklistEmpty: "ابھی کسی کیس کو جائزے کی ضرورت نہیں۔",
  lblResult: "نتیجہ",
  lblHistory: "سابقہ اسکریننگ تاریخ",
  lblMedicine: "درج دوا",
  lblRules: "لاگو قواعد",
  lblReminders: "یاد دہانیاں",
  remindersNoReply: "دن 3 اور 7 کو بھیجی گئیں، کوئی تصدیق نہیں",
  yes: "ہاں", no: "نہیں", none: "کوئی نہیں",
  medCheck: "دوا کا سیاق",
  medCheckD: "ایک دوا درج ہے۔ نظام نہیں جانتا کہ یہ کیوں تجویز کی گئی؛ نتیجے کا زمرہ نہیں بدلا جاتا۔",
  routedMed: "انسانی جائزہ کار کو بھیجا گیا (RULE-004)",
  routedMedD: "دوا کی وجہ معلوم نہیں، اس لیے کچھ بھیجنے سے پہلے کسی شخص کو راستہ جانچنا ہوگا۔",
  engWaitD5: "جائزے کا انتظار — یاد دہانیاں جائزہ کار کی تصدیق کے بعد ہی شروع ہوں گی۔",
  engWaitD6: "جائزے کا انتظار: انسانی جائزہ کار کو بھیجا گیا ({rule})۔",
  engReferralD4: "ریفرل: جائزے کے بعد فالو اپ ڈاکٹر طے کرے گا۔ 3/6/12 ماہ کا شیڈول نہیں۔",
  careTeamTitle: "نگہداشت ٹیم (ڈیمو)",
  careTeamDesc: "اس پروٹوٹائپ کے فرضی ڈاکٹر۔ دکھائی گئی تمام اسناد مصنوعی ڈیمو ڈیٹا ہیں۔",
  lblSpecialty: "شعبہ",
  lblHospital: "ہسپتال",
  specFamily: "فیملی میڈیسن",
  specEndo: "اینڈوکرائنولوجی",
  hospA: "ڈیمو فیملی ہیلتھ سینٹر — جمیرا",
  hospB: "ڈیمو پرائمری کیئر کلینک — دیرہ",
  credNote: "اس پروٹوٹائپ میں اسناد کی تصدیق نہیں ہوتی۔ حقیقی استعمال میں تصدیق شدہ حیثیت دینے سے پہلے جائزہ کاروں کی متعلقہ لائسنسنگ اتھارٹی سے تصدیق کی جائے گی۔",
  lblRole: "کردار",
  lblLicense: "میڈیکل لائسنس نمبر",
  lblAuthority: "لائسنسنگ اتھارٹی",
  lblLicenseExpiry: "لائسنس کی میعاد",
  lblCerts: "سرٹیفیکیشنز",
  lblCertExpiry: "سرٹیفیکیشن کی میعاد",
  lblVerification: "تصدیق کی حیثیت",
  lblFullName: "پورا نام",
  roleValue: "معالج",
  authorityDoH: "UAE DoH",
  certFamily: "فیملی میڈیسن سرٹیفیکیشن",
  certEndo: "اینڈوکرائنولوجی سرٹیفیکیشن",
  statusDemo: "ڈیمو — غیر تصدیق شدہ",
  statusNotVerified: "غیر تصدیق شدہ",
  viewCreds: "اسناد دیکھیں",
  hideCreds: "اسناد چھپائیں",
  addDoctor: "+ ڈاکٹر شامل کریں",
  saveDoctor: "ڈاکٹر محفوظ کریں",
  cancelDoctor: "منسوخ",
  errRequired: "براہ کرم ہر خانہ پُر کریں۔",
  demoBadge: "مصنوعی ڈیمو ڈیٹا",
  addedNote: "صرف اس سیشن میں شامل کیا گیا۔ حیثیت غیر تصدیق شدہ رہتی ہے؛ یہ پروٹوٹائپ لائسنس کی تصدیق نہیں کر سکتا۔",
  cohortLabel: "مصنوعی گروپ، صرف وضاحت کے لیے۔",
  fScreened: "اسکرین ہوئے", fResulted: "نتائج آئے", fFlagged: "نشان زد",
  fConfirmed: "تصدیق کی", fLocation: "مقام چنا", fBooked: "بک کیا", fCompleted: "وزٹ مکمل",
  ofScreened: "اسکرین شدہ کا {p}%",
  ofFlagged: "نشان زد کا {p}%",
  screeningFunnel: "اسکریننگ",
  followFunnel: "نشان زد افراد میں فالو تھرو",
  attention: "توجہ درکار",
  aNotConfirmed: "نشان زد، تصدیق نہیں",
  aNotBooked: "تصدیق کی، بک نہیں",
  aNotCompleted: "بک کیا، وزٹ مکمل نہیں",
  caseSelect: "کیس",
  caseEvents: "کیس کے واقعات (مشترکہ کیس ڈیٹا سے)",
  secTitle: "سیکیورٹی اور ڈیٹا تحفظ",
  secTrue: "اس پروٹوٹائپ کے بارے میں درست",
  secT1: "صرف مصنوعی ڈیٹا۔",
  secT2: "براؤزر میں کوئی AI کلید نہیں۔",
  secT3: "نظام کبھی تشخیص نہیں کرتا۔",
  secT4: "ہر فیصلہ ایک اصول ID سے منسلک ہے۔ طبی حدود UAE DoH معیار کا حوالہ دیتی ہیں؛ RULE-003 اور RULE-004 پروٹوٹائپ کے حفاظتی اصول ہیں۔",
  secReq: "حقیقی ڈیٹا سے پہلے ضروری",
  secR1: "انکرپشن", secR2: "حقیقی تصدیق", secR3: "UAE ڈیٹا ریزیڈنسی", secR4: "چھیڑ چھاڑ ظاہر کرنے والا سرور اسٹوریج", secR5: "سیکیورٹی جائزہ", secR6: "طبی توثیق", secR7: "نتائج اور فالو اپ کی حیثیت کے لیے Malaffi، Nabidh اور Riayati — امارات کے ہیلتھ انفارمیشن ایکسچینج — سے براہِ راست رابطہ۔",
  secModel: "یہ پروٹوٹائپ کوئی AI ماڈل استعمال نہیں کرتا۔ حقیقی استعمال میں اسے صرف تصویر والی پرچی کو متن میں پڑھنے کے لیے استعمال کیا جا سکتا ہے؛ ہر فیصلہ پھر بھی اصولوں سے ہوگا۔",
  tabNeeds: "جائزہ درکار",
  tabAll: "تمام کیس",
  tabReviewed: "جائزہ شدہ",
  colReviewNeeded: "جائزہ درکار؟",
  colEngineReason: "انجن کی وجہ",
  colDecision: "فیصلہ",
  colTime: "وقت",
  colReviewer: "جائزہ کار",
  erPre: "پری ذیابیطس کی حد، اسکریننگ کی تاریخ درج، کوئی دوا نہیں: راستہ بغیر جائزے کے بھیجا گیا۔",
  erReferral: "ریفرل کی حد: براہ راست معالج کے جائزے کے لیے بھیجا گیا، جائزے کی ضرورت نہیں۔",
  erNormal: "پری ذیابیطس کی حد سے کم: فالو اپ کی ضرورت نہیں۔",
  progAwaiting: "جائزہ کار کا انتظار",
  progConfirmed: "جائزہ کار نے تصدیق کی",
  progAdjusted: "جائزہ کار نے تبدیل کیا",
  progEscalated: "آگے بڑھایا گیا",
  progNotEscalated: "آگے نہیں بڑھایا گیا",
  reviewedEmpty: "ابھی تک کسی کیس کا جائزہ نہیں ہوا۔",
  sampleNote: "پانچ نامزد نمونہ کیس دکھاتا ہے۔ آبادی کا فنل ایک الگ مصنوعی گروپ ہے۔",
  funnelDef: "نشان زد = نتیجہ پری ذیابیطس یا ریفرل کی حد میں۔ تصدیق شدہ = مریض نے فالو اپ منصوبہ قبول کیا۔",
  largestLoss: "سب سے بڑی فنل کمی: {from} ← {to} — {n} افراد ({p}%) {why}.",
  lossNotFlagged: "طے شدہ حدود کے مطابق نشان زد نہیں ہوئے",
  lossGeneric: "اگلے مرحلے تک نہیں پہنچے",
  mohap: "MOHAP کی قومی مہم میں، پری ذیابیطس کی نشاندہی کے بعد طرزِ زندگی کی رہنمائی پر عمل کرنے والوں میں سے 8.1% چھ ماہ میں نارمل HbA1c پر واپس آئے اور 1% ٹائپ 2 ذیابیطس تک پہنچے۔",
  auditRecordedD: "{test} {value} اسکریننگ لیب سے موصول ہوا اور کیس سے منسلک کیا گیا۔",
};
const tl: D = {
  demoNoticeLabel: "Demo para sa presentasyon", liveNoticeLabel: "Aktwal na deployment",
  demoLogin: "Pumili ng role at maglagay ng mukhang valid na detalye upang buksan ang presentasyon; walang account na ina-authenticate.", liveLogin: "Magsa-sign in ang mga pasyente at clinician gamit ang verified at role-based identity controls.",
  demoResult: "Baguhin ang value upang ipakita ang deterministic pathway; hindi ito sine-save o ipinapadala sa clinical record.", liveResult: "Manggagaling ang validated results sa aprubadong sources at iuugnay sa authenticated patient record.",
  demoReminder: "Ang pagdagdag o pagtanggal ng paalala ay sa session na ito lamang; walang notification na ipinapadala.", liveReminder: "Ise-schedule ang aprubadong reminders sa secure notification service na may delivery records.",
  demoPatient: "Pumili ng nakatakdang synthetic na pasyente upang ipakita ang bawat pathway.", livePatient: "Ang authenticated na pasyente ay sariling live case record lamang ang makikita.",
  demoTime: "Ginagawang mga click ng mga button ang araw 3, 7 at 14; walang mensaheng ipinapadala.", liveTime: "Magpapadala ang scheduler ng aprubadong paalala sa tunay na petsa at ligtas na itatala ang delivery.",
  demoReview: "Gamitin ang sample cases at reviewer actions upang ipakita ang daloy ng desisyon; walang clinician o health record na kinokontak.", liveReview: "Susuriin ng awtorisadong clinician ang nakatalagang live cases at itatago ang desisyon sa matibay na audit record.",
  demoDoctor: "Pumili ng kathang-isip na doktor upang ipakita ang clinician views; sa session na ito lamang mananatili ang idinagdag na doktor.", liveDoctor: "Gagamit ang authenticated clinicians ng sariling profile at pamamahalaan ng admin ang aprubadong care-team records.",
  demoCredential: "Synthetic session data lamang ang nababago ng pagsusumite, pag-upload, o pagmarka ng credential.", liveCredential: "Ibe-verify ng awtorisadong reviewer ang identity at credentials sa aprubadong licensing sources bago magbigay ng access.",
  demoAudit: "Pumili ng synthetic case upang ipakita ang scripted at session activity nito.", liveAudit: "Makikita ng awtorisadong user ang access-controlled at tamper-evident record ng kaugnay na tunay na kaso.",
  demoEngine: "Pumili ng isa sa limang nakatakdang synthetic cases at ulitin ang rule steps; walang clinical system na kinokontak.", liveEngine: "Papasok ang validated screening data sa aprubadong rules service upang lumikha ng masusubaybayang susunod na hakbang para sa tamang pasyente.",
  simTitle: "Demo: i-simulate ang oras",
  simDesc: "Isulong ang kasong ito para makita kung ano ang mangyayari kapag hindi nakumpirma ang follow-up.",
  simDay: "I-simulate ang araw {n}",
  simReset: "I-reset",
  simCurrent: "Simulated na araw: {n}",
  simStopped: "Nakumpirma ang follow-up — huminto ang mga paalala.",
  simEscalated: "Araw 14 nang walang kumpirmasyon: hiniling sa care team na suriin.",
  notifReminder: "Paalala sa follow-up",
  notifReminderDesc: "Araw {n}: pakikumpirma ang iyong health follow-up.",
  auditReminder: "Naipadala ang paalala (simulated na araw {n})",
  auditEscalated: "Walang kumpirmasyon sa araw 14, in-escalate",
  auditQuestionSent: "Ipinasa ang tanong sa care team (hindi naka-save ang teksto sa audit trail)",
  askEid: "Huwag isama ang Emirates ID sa iyong tanong.",
  reasonNoHistory: "Walang naunang screening history",
  reasonMedication: "Hindi malinaw ang konteksto ng gamot",
  reasonDay14: "Walang kumpirmasyon sa araw 14, in-escalate",
  nextStepHeader: "Susunod na hakbang",
  nsReview: "Reviewer: Confirm / Adjust / Escalate ang pathway",
  nsDay14: "Kokontakin ng reviewer ang pasyente: Confirm / Adjust / Escalate",
  worklistEmpty: "Walang kasong kailangang suriin ngayon.",
  lblResult: "Resulta",
  lblHistory: "Naunang screening history",
  lblMedicine: "Gamot na nakatala",
  lblRules: "Mga panuntunang ginamit",
  lblReminders: "Mga paalala",
  remindersNoReply: "Naipadala sa araw 3 at 7, walang kumpirmasyon",
  yes: "Oo", no: "Hindi", none: "Wala",
  medCheck: "Konteksto ng gamot",
  medCheckD: "May gamot na nakatala. Hindi alam ng sistema kung bakit ito inireseta; hindi binabago ang band ng resulta.",
  routedMed: "Ipinasa sa isang taong reviewer (RULE-004)",
  routedMedD: "Hindi alam ang dahilan ng gamot, kaya dapat suriin ng isang tao ang pathway bago magpadala ng anuman.",
  engWaitD5: "Naghihintay ng pagsusuri — magsisimula lang ang mga paalala kapag kinumpirma ng reviewer.",
  engWaitD6: "Naghihintay ng pagsusuri: ipinasa sa taong reviewer ({rule}).",
  engReferralD4: "Referral: ang clinician ang magtatakda ng follow-up pagkatapos ng pagsusuri. Walang 3/6/12 buwang iskedyul.",
  careTeamTitle: "Care team (demo)",
  careTeamDesc: "Mga kathang-isip na doktor para sa prototype na ito. Lahat ng credential ay synthetic demo data.",
  lblSpecialty: "Espesyalidad",
  lblHospital: "Ospital",
  specFamily: "Family medicine",
  specEndo: "Endocrinology",
  hospA: "Demo Family Health Centre — Jumeirah",
  hospB: "Demo Primary Care Clinic — Deira",
  credNote: "Walang credential verification sa prototype na ito. Sa aktwal na deployment, ive-verify ang mga reviewer sa kaukulang licensing authority bago bigyan ng verified status.",
  lblRole: "Tungkulin",
  lblLicense: "Numero ng medical license",
  lblAuthority: "Licensing authority",
  lblLicenseExpiry: "Pag-expire ng license",
  lblCerts: "Mga sertipikasyon",
  lblCertExpiry: "Pag-expire ng sertipikasyon",
  lblVerification: "Status ng verification",
  lblFullName: "Buong pangalan",
  roleValue: "Doktor",
  authorityDoH: "UAE DoH",
  certFamily: "Family Medicine Certification",
  certEndo: "Endocrinology Certification",
  statusDemo: "DEMO — HINDI VERIFIED",
  statusNotVerified: "Hindi verified",
  viewCreds: "Tingnan ang credentials",
  hideCreds: "Itago ang credentials",
  addDoctor: "+ Magdagdag ng doktor",
  saveDoctor: "I-save ang doktor",
  cancelDoctor: "Kanselahin",
  errRequired: "Pakipunan ang bawat field.",
  demoBadge: "Synthetic demo data",
  addedNote: "Idinagdag sa session na ito lang. Mananatiling Hindi verified; hindi kayang i-verify ng prototype ang mga license.",
  cohortLabel: "Sintetikong cohort, halimbawa lamang.",
  fScreened: "Na-screen", fResulted: "May resulta", fFlagged: "Na-flag",
  fConfirmed: "Nakumpirma", fLocation: "Pumili ng lokasyon", fBooked: "Naka-book", fCompleted: "Tapos ang pagbisita",
  ofScreened: "{p}% ng na-screen",
  ofFlagged: "{p}% ng na-flag",
  screeningFunnel: "Screening",
  followFunnel: "Follow-through ng mga na-flag",
  attention: "Kailangan ng pansin",
  aNotConfirmed: "Na-flag, hindi nakumpirma",
  aNotBooked: "Nakumpirma, hindi naka-book",
  aNotCompleted: "Naka-book, hindi tapos ang pagbisita",
  caseSelect: "Kaso",
  caseEvents: "Mga pangyayari sa kaso (mula sa shared case data)",
  secTitle: "Seguridad at proteksyon ng datos",
  secTrue: "Totoo sa prototype na ito",
  secT1: "Sintetikong datos lamang.",
  secT2: "Walang AI key sa browser.",
  secT3: "Hindi kailanman nagda-diagnose ang sistema.",
  secT4: "Bawat desisyon ay natutunton sa isang rule ID. Ang mga clinical threshold ay batay sa pamantayan ng UAE DoH; ang RULE-003 at RULE-004 ay mga safety rule ng prototype.",
  secReq: "Kailangan bago gumamit ng totoong datos",
  secR1: "Encryption", secR2: "Totoong authentication", secR3: "Data residency sa UAE", secR4: "Tamper-evident na server-side storage", secR5: "Security review", secR6: "Klinikal na validation", secR7: "Direktang koneksyon sa Malaffi, Nabidh at Riayati — mga health information exchange ng UAE — para sa mga resulta at status ng follow-up.",
  secModel: "Walang AI model na ginagamit ang prototype na ito. Sa aktwal na paggamit, maaari lang itong gamitin para basahin ang litrato ng slip bilang text; lahat ng desisyon ay manggagaling pa rin sa mga rule.",
  tabNeeds: "Kailangang suriin",
  tabAll: "Lahat ng kaso",
  tabReviewed: "Nasuri na",
  colReviewNeeded: "Kailangang suriin?",
  colEngineReason: "Dahilan ng engine",
  colDecision: "Desisyon",
  colTime: "Oras",
  colReviewer: "Reviewer",
  erPre: "Nasa prediabetes range, may screening history, walang gamot: ipinadala ang pathway nang walang review.",
  erReferral: "Nasa referral range: diretsong ipinadala sa pagsusuri ng clinician, hindi kailangan ng review.",
  erNormal: "Mas mababa sa prediabetes range: walang kailangang follow-up.",
  progAwaiting: "Naghihintay ng reviewer",
  progConfirmed: "Kinumpirma ng reviewer",
  progAdjusted: "Binago ng reviewer",
  progEscalated: "Na-escalate",
  progNotEscalated: "Hindi na-escalate",
  reviewedEmpty: "Wala pang nasuring kaso.",
  sampleNote: "Ipinapakita ang limang pinangalanang sample na kaso. Ang population funnel ay hiwalay na synthetic cohort.",
  funnelDef: "Flagged = resulta sa prediabetes o referral range. Confirmed = tinanggap ng pasyente ang follow-up plan.",
  largestLoss: "Pinakamalaking pagbaba sa funnel: {from} → {to} — {n} tao ({p}%) {why}.",
  lossNotFlagged: "hindi na-flag batay sa mga itinakdang threshold",
  lossGeneric: "hindi nagpatuloy sa susunod na hakbang",
  mohap: "Sa pambansang kampanya ng MOHAP, sa mga taong sumunod sa gabay sa pamumuhay matapos ma-flag na prediabetic, 8.1% ang bumalik sa normal na HbA1c sa loob ng anim na buwan at 1% ang nauwi sa type 2 diabetes.",
  auditRecordedD: "Natanggap ang {test} {value} mula sa screening lab at idinagdag sa kaso.",
};
const ml: D = {
  demoNoticeLabel: "അവതരണ ഡെമോ", liveNoticeLabel: "യഥാർത്ഥ വിന്യാസം",
  demoLogin: "അവതരണം തുറക്കാൻ ഒരു റോൾ തിരഞ്ഞെടുത്ത് ശരിയായി തോന്നുന്ന വിവരങ്ങൾ നൽകുക; അക്കൗണ്ട് സ്ഥിരീകരിക്കുന്നില്ല.", liveLogin: "രോഗികളും ക്ലിനീഷ്യന്മാരും സ്ഥിരീകരിച്ചതും റോൾ അടിസ്ഥാനത്തിലുള്ളതുമായ തിരിച്ചറിയൽ നിയന്ത്രണങ്ങളിലൂടെ സൈൻ ഇൻ ചെയ്യും.",
  demoResult: "നിശ്ചിത പാത അവതരിപ്പിക്കാൻ മൂല്യം മാറ്റുക; ഇത് ക്ലിനിക്കൽ രേഖയിൽ സൂക്ഷിക്കുകയോ അയയ്ക്കുകയോ ഇല്ല.", liveResult: "സാധൂകരിച്ച ഫലങ്ങൾ അംഗീകൃത ഉറവിടങ്ങളിൽ നിന്ന് എത്തി സ്ഥിരീകരിച്ച രോഗി രേഖയുമായി ബന്ധിപ്പിക്കും.",
  demoReminder: "ഓർമ്മപ്പെടുത്തൽ ചേർക്കുന്നതോ നീക്കുന്നതോ ഈ സെഷൻ മാത്രം മാറ്റുന്നു; അറിയിപ്പ് അയയ്ക്കുന്നില്ല.", liveReminder: "അംഗീകൃത ഓർമ്മപ്പെടുത്തലുകൾ സുരക്ഷിത അറിയിപ്പ് സേവനത്തിലൂടെ ഷെഡ്യൂൾ ചെയ്ത് ഡെലിവറി രേഖപ്പെടുത്തും.",
  demoPatient: "ഓരോ പാതയും അവതരിപ്പിക്കാൻ ഒരു നിശ്ചിത സിന്തറ്റിക് രോഗിയെ തിരഞ്ഞെടുക്കുക.", livePatient: "സ്ഥിരീകരിച്ച രോഗി സ്വന്തം തത്സമയ കേസ് രേഖ മാത്രം കാണും.",
  demoTime: "ബട്ടണുകൾ ദിവസം 3, 7, 14 എന്നിവ ക്ലിക്കുകളാക്കി ചുരുക്കുന്നു; സന്ദേശമൊന്നും അയയ്ക്കില്ല.", liveTime: "ഷെഡ്യൂളർ യഥാർത്ഥ തീയതികളിൽ അംഗീകൃത ഓർമ്മപ്പെടുത്തലുകൾ അയച്ച് ഡെലിവറി സുരക്ഷിതമായി രേഖപ്പെടുത്തും.",
  demoReview: "തീരുമാന പ്രവാഹം അവതരിപ്പിക്കാൻ സാമ്പിൾ കേസുകളും റിവ്യൂവർ നടപടികളും ഉപയോഗിക്കുക; ക്ലിനീഷ്യനെയോ ആരോഗ്യ രേഖയെയോ ബന്ധപ്പെടുന്നില്ല.", liveReview: "അധികാരമുള്ള ക്ലിനീഷ്യന്മാർ നിയോഗിച്ച തത്സമയ കേസുകൾ പരിശോധിച്ച് തീരുമാനങ്ങൾ സ്ഥിരമായ ഓഡിറ്റ് രേഖയിൽ സൂക്ഷിക്കും.",
  demoDoctor: "ക്ലിനീഷ്യൻ കാഴ്ചകൾ അവതരിപ്പിക്കാൻ സാങ്കൽപ്പിക ഡോക്ടറെ തിരഞ്ഞെടുക്കുക; ചേർത്ത ഡോക്ടർ ഈ സെഷനിൽ മാത്രം നിലനിൽക്കും.", liveDoctor: "സ്ഥിരീകരിച്ച ക്ലിനീഷ്യന്മാർ സ്വന്തം പ്രൊഫൈൽ ഉപയോഗിക്കും; അംഗീകൃത കെയർ-ടീം രേഖകൾ അഡ്മിനിസ്ട്രേറ്റർമാർ നിയന്ത്രിക്കും.",
  demoCredential: "സമർപ്പിക്കൽ, അപ്‌ലോഡ്, അല്ലെങ്കിൽ സ്ഥിരീകരണ അടയാളപ്പെടുത്തൽ സിന്തറ്റിക് സെഷൻ ഡാറ്റ മാത്രം മാറ്റുന്നു.", liveCredential: "പ്രവേശനം നൽകുന്നതിന് മുമ്പ് അധികാരമുള്ള റിവ്യൂവർമാർ അംഗീകൃത ലൈസൻസിംഗ് ഉറവിടങ്ങളിൽ നിന്ന് തിരിച്ചറിയലും യോഗ്യതകളും പരിശോധിക്കും.",
  demoAudit: "സ്ക്രിപ്റ്റ് ചെയ്തതും സെഷനിലേതുമായ പ്രവർത്തനം അവതരിപ്പിക്കാൻ ഒരു സിന്തറ്റിക് കേസ് തിരഞ്ഞെടുക്കുക.", liveAudit: "ബന്ധപ്പെട്ട യഥാർത്ഥ കേസിന്റെ പ്രവേശനനിയന്ത്രിതവും തിരിമറി തെളിയിക്കുന്നതുമായ രേഖ അധികാരമുള്ളവർ കാണും.",
  demoEngine: "അഞ്ച് നിശ്ചിത സിന്തറ്റിക് കേസുകളിൽ ഒന്ന് തിരഞ്ഞെടുത്ത് നിയമ ഘട്ടങ്ങൾ വീണ്ടും പ്രവർത്തിപ്പിക്കുക; ക്ലിനിക്കൽ സിസ്റ്റവുമായി ബന്ധപ്പെടുന്നില്ല.", liveEngine: "സാധൂകരിച്ച സ്ക്രീനിംഗ് ഡാറ്റ അംഗീകൃത റൂൾ സേവനത്തിലെത്തി ശരിയായ രോഗിക്ക് പിന്തുടരാവുന്ന അടുത്ത ഘട്ടം സൃഷ്ടിക്കും.",
  simTitle: "ഡെമോ: സമയം സിമുലേറ്റ് ചെയ്യുക",
  simDesc: "ഫോളോ-അപ്പ് സ്ഥിരീകരിക്കാത്തപ്പോൾ എന്ത് സംഭവിക്കുമെന്ന് കാണാൻ ഈ കേസ് മുന്നോട്ട് നീക്കുക.",
  simDay: "ദിവസം {n} സിമുലേറ്റ് ചെയ്യുക",
  simReset: "റീസെറ്റ്",
  simCurrent: "സിമുലേറ്റ് ചെയ്ത ദിവസം: {n}",
  simStopped: "ഫോളോ-അപ്പ് സ്ഥിരീകരിച്ചു — ഓർമ്മപ്പെടുത്തലുകൾ നിർത്തി.",
  simEscalated: "ദിവസം 14 വരെ സ്ഥിരീകരണമില്ല: കെയർ ടീമിനോട് അവലോകനം ചെയ്യാൻ ആവശ്യപ്പെട്ടു.",
  notifReminder: "ഫോളോ-അപ്പ് ഓർമ്മപ്പെടുത്തൽ",
  notifReminderDesc: "ദിവസം {n}: നിങ്ങളുടെ ആരോഗ്യ ഫോളോ-അപ്പ് സ്ഥിരീകരിക്കുക.",
  auditReminder: "ഓർമ്മപ്പെടുത്തൽ അയച്ചു (സിമുലേറ്റ് ദിവസം {n})",
  auditEscalated: "ദിവസം 14 വരെ സ്ഥിരീകരണമില്ല, എസ്കലേറ്റ് ചെയ്തു",
  auditQuestionSent: "ചോദ്യം കെയർ ടീമിലേക്ക് അയച്ചു (വാചകം ഓഡിറ്റ് ട്രെയിലിൽ സൂക്ഷിക്കുന്നില്ല)",
  askEid: "ദയവായി ചോദ്യത്തിൽ എമിറേറ്റ്സ് ഐഡി ഉൾപ്പെടുത്തരുത്.",
  reasonNoHistory: "മുൻ സ്ക്രീനിംഗ് ചരിത്രം ഇല്ല",
  reasonMedication: "മരുന്നിന്റെ സന്ദർഭം വ്യക്തമല്ല",
  reasonDay14: "ദിവസം 14 വരെ സ്ഥിരീകരണമില്ല, എസ്കലേറ്റ് ചെയ്തു",
  nextStepHeader: "അടുത്ത ഘട്ടം",
  nsReview: "റിവ്യൂവർ: പാത്ത്‌വേ സ്ഥിരീകരിക്കുക / മാറ്റുക / എസ്കലേറ്റ്",
  nsDay14: "റിവ്യൂവർ രോഗിയെ ബന്ധപ്പെടും: സ്ഥിരീകരിക്കുക / മാറ്റുക / എസ്കലേറ്റ്",
  worklistEmpty: "ഇപ്പോൾ അവലോകനം ആവശ്യമുള്ള കേസുകളില്ല.",
  lblResult: "ഫലം",
  lblHistory: "മുൻ സ്ക്രീനിംഗ് ചരിത്രം",
  lblMedicine: "രേഖപ്പെടുത്തിയ മരുന്ന്",
  lblRules: "പ്രയോഗിച്ച നിയമങ്ങൾ",
  lblReminders: "ഓർമ്മപ്പെടുത്തലുകൾ",
  remindersNoReply: "ദിവസം 3, 7 അയച്ചു, സ്ഥിരീകരണമില്ല",
  yes: "അതെ", no: "ഇല്ല", none: "ഒന്നുമില്ല",
  medCheck: "മരുന്നിന്റെ സന്ദർഭം",
  medCheckD: "ഒരു മരുന്ന് രേഖയിലുണ്ട്. അത് എന്തിനാണ് നിർദ്ദേശിച്ചതെന്ന് സിസ്റ്റത്തിന് അറിയില്ല; ഫല വിഭാഗം മാറ്റുന്നില്ല.",
  routedMed: "ഒരു മനുഷ്യ റിവ്യൂവറിലേക്ക് അയച്ചു (RULE-004)",
  routedMedD: "മരുന്നിന്റെ കാരണം അറിയില്ല, അതിനാൽ എന്തെങ്കിലും അയയ്ക്കുന്നതിന് മുമ്പ് ഒരാൾ പാത പരിശോധിക്കണം.",
  engWaitD5: "അവലോകനത്തിനായി കാത്തിരിക്കുന്നു — റിവ്യൂവർ സ്ഥിരീകരിച്ച ശേഷം മാത്രമേ ഓർമ്മപ്പെടുത്തലുകൾ തുടങ്ങൂ.",
  engWaitD6: "അവലോകനത്തിനായി കാത്തിരിക്കുന്നു: മനുഷ്യ റിവ്യൂവറിലേക്ക് അയച്ചു ({rule}).",
  engReferralD4: "റഫറൽ: വിലയിരുത്തലിന് ശേഷം ഡോക്ടർ ഫോളോ-അപ്പ് നിശ്ചയിക്കും. 3/6/12 മാസ ഷെഡ്യൂൾ ഇല്ല.",
  careTeamTitle: "കെയർ ടീം (ഡെമോ)",
  careTeamDesc: "ഈ പ്രോട്ടോടൈപ്പിനുള്ള സാങ്കൽപ്പിക ഡോക്ടർമാർ. കാണിക്കുന്ന എല്ലാ യോഗ്യതകളും സിന്തറ്റിക് ഡെമോ ഡാറ്റയാണ്.",
  lblSpecialty: "സ്പെഷ്യാലിറ്റി",
  lblHospital: "ആശുപത്രി",
  specFamily: "ഫാമിലി മെഡിസിൻ",
  specEndo: "എൻഡോക്രൈനോളജി",
  hospA: "ഡെമോ ഫാമിലി ഹെൽത്ത് സെന്റർ — ജുമൈറ",
  hospB: "ഡെമോ പ്രൈമറി കെയർ ക്ലിനിക് — ദേര",
  credNote: "ഈ പ്രോട്ടോടൈപ്പിൽ യോഗ്യതാ പരിശോധന നടക്കുന്നില്ല. യഥാർത്ഥ ഉപയോഗത്തിൽ സ്ഥിരീകരിച്ച പദവി നൽകുന്നതിന് മുമ്പ് റിവ്യൂവർമാരെ ബന്ധപ്പെട്ട ലൈസൻസിംഗ് അതോറിറ്റിയുമായി പരിശോധിക്കും.",
  lblRole: "റോൾ",
  lblLicense: "മെഡിക്കൽ ലൈസൻസ് നമ്പർ",
  lblAuthority: "ലൈസൻസിംഗ് അതോറിറ്റി",
  lblLicenseExpiry: "ലൈസൻസ് കാലാവധി",
  lblCerts: "സർട്ടിഫിക്കേഷനുകൾ",
  lblCertExpiry: "സർട്ടിഫിക്കേഷൻ കാലാവധി",
  lblVerification: "സ്ഥിരീകരണ നില",
  lblFullName: "പൂർണ്ണ നാമം",
  roleValue: "ഫിസിഷ്യൻ",
  authorityDoH: "UAE DoH",
  certFamily: "ഫാമിലി മെഡിസിൻ സർട്ടിഫിക്കേഷൻ",
  certEndo: "എൻഡോക്രൈനോളജി സർട്ടിഫിക്കേഷൻ",
  statusDemo: "ഡെമോ — സ്ഥിരീകരിച്ചിട്ടില്ല",
  statusNotVerified: "സ്ഥിരീകരിച്ചിട്ടില്ല",
  viewCreds: "യോഗ്യതകൾ കാണുക",
  hideCreds: "യോഗ്യതകൾ മറയ്ക്കുക",
  addDoctor: "+ ഡോക്ടറെ ചേർക്കുക",
  saveDoctor: "ഡോക്ടറെ സേവ് ചെയ്യുക",
  cancelDoctor: "റദ്ദാക്കുക",
  errRequired: "എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക.",
  demoBadge: "സിന്തറ്റിക് ഡെമോ ഡാറ്റ",
  addedNote: "ഈ സെഷനിൽ മാത്രം ചേർത്തത്. നില 'സ്ഥിരീകരിച്ചിട്ടില്ല' ആയി തുടരും; ഈ പ്രോട്ടോടൈപ്പിന് ലൈസൻസുകൾ പരിശോധിക്കാനാവില്ല.",
  cohortLabel: "സിന്തറ്റിക് കോഹോർട്ട്, ഉദാഹരണത്തിന് മാത്രം.",
  fScreened: "സ്ക്രീൻ ചെയ്തവർ", fResulted: "ഫലം ലഭിച്ചവർ", fFlagged: "ഫ്ലാഗ് ചെയ്തവർ",
  fConfirmed: "സ്ഥിരീകരിച്ചു", fLocation: "സ്ഥലം തിരഞ്ഞെടുത്തു", fBooked: "ബുക്ക് ചെയ്തു", fCompleted: "സന്ദർശനം പൂർത്തിയായി",
  ofScreened: "സ്ക്രീൻ ചെയ്തവരുടെ {p}%",
  ofFlagged: "ഫ്ലാഗ് ചെയ്തവരുടെ {p}%",
  screeningFunnel: "സ്ക്രീനിംഗ്",
  followFunnel: "ഫ്ലാഗ് ചെയ്തവരിലെ ഫോളോ-ത്രൂ",
  attention: "ശ്രദ്ധ ആവശ്യം",
  aNotConfirmed: "ഫ്ലാഗ് ചെയ്തു, സ്ഥിരീകരിച്ചില്ല",
  aNotBooked: "സ്ഥിരീകരിച്ചു, ബുക്ക് ചെയ്തില്ല",
  aNotCompleted: "ബുക്ക് ചെയ്തു, സന്ദർശനം പൂർത്തിയായില്ല",
  caseSelect: "കേസ്",
  caseEvents: "കേസ് സംഭവങ്ങൾ (പങ്കിട്ട കേസ് ഡാറ്റയിൽ നിന്ന്)",
  secTitle: "സുരക്ഷയും ഡാറ്റ സംരക്ഷണവും",
  secTrue: "ഈ പ്രോട്ടോടൈപ്പിനെക്കുറിച്ച് ശരിയായത്",
  secT1: "സിന്തറ്റിക് ഡാറ്റ മാത്രം.",
  secT2: "ബ്രൗസറിൽ AI കീ ഇല്ല.",
  secT3: "സിസ്റ്റം ഒരിക്കലും രോഗനിർണയം നടത്തുന്നില്ല.",
  secT4: "ഓരോ തീരുമാനവും ഒരു റൂൾ ID-യിലേക്ക് എത്തുന്നു. ക്ലിനിക്കൽ പരിധികൾ UAE DoH മാനദണ്ഡം ഉദ്ധരിക്കുന്നു; RULE-003, RULE-004 എന്നിവ പ്രോട്ടോടൈപ്പ് സുരക്ഷാ നിയമങ്ങളാണ്.",
  secReq: "യഥാർത്ഥ ഡാറ്റയ്ക്ക് മുമ്പ് ആവശ്യമായവ",
  secR1: "എൻക്രിപ്ഷൻ", secR2: "യഥാർത്ഥ ഓതന്റിക്കേഷൻ", secR3: "UAE ഡാറ്റ റെസിഡൻസി", secR4: "തിരിമറി തെളിയിക്കുന്ന സെർവർ സംഭരണം", secR5: "സുരക്ഷാ അവലോകനം", secR6: "ക്ലിനിക്കൽ സാധൂകരണം", secR7: "ഫലങ്ങൾക്കും ഫോളോ-അപ്പ് നിലയ്ക്കും Malaffi, Nabidh, Riayati — യുഎഇ ഹെൽത്ത് ഇൻഫർമേഷൻ എക്സ്ചേഞ്ചുകൾ — എന്നിവയുമായുള്ള നേരിട്ടുള്ള ബന്ധം.",
  secModel: "ഈ പ്രോട്ടോടൈപ്പ് AI മോഡൽ ഉപയോഗിക്കുന്നില്ല. യഥാർത്ഥ ഉപയോഗത്തിൽ ഫോട്ടോ എടുത്ത സ്ലിപ്പ് ടെക്സ്റ്റാക്കി വായിക്കാൻ മാത്രം ഒന്ന് ഉപയോഗിക്കാം; എല്ലാ തീരുമാനങ്ങളും നിയമങ്ങളിൽ നിന്നുതന്നെ വരും.",
  tabNeeds: "അവലോകനം ആവശ്യം",
  tabAll: "എല്ലാ കേസുകളും",
  tabReviewed: "അവലോകനം ചെയ്തവ",
  colReviewNeeded: "അവലോകനം വേണോ?",
  colEngineReason: "എഞ്ചിന്റെ കാരണം",
  colDecision: "തീരുമാനം",
  colTime: "സമയം",
  colReviewer: "റിവ്യൂവർ",
  erPre: "പ്രീഡയബറ്റിസ് പരിധി, സ്ക്രീനിംഗ് ചരിത്രം ഉണ്ട്, മരുന്നില്ല: അവലോകനം കൂടാതെ പാത അയച്ചു.",
  erReferral: "റഫറൽ പരിധി: നേരിട്ട് ക്ലിനീഷ്യന്റെ വിലയിരുത്തലിന് അയച്ചു, അവലോകനം ആവശ്യമില്ല.",
  erNormal: "പ്രീഡയബറ്റിസ് പരിധിക്ക് താഴെ: ഫോളോ-അപ്പ് ആവശ്യമില്ല.",
  progAwaiting: "റിവ്യൂവറെ കാത്തിരിക്കുന്നു",
  progConfirmed: "റിവ്യൂവർ സ്ഥിരീകരിച്ചു",
  progAdjusted: "റിവ്യൂവർ മാറ്റി",
  progEscalated: "എസ്കലേറ്റ് ചെയ്തു",
  progNotEscalated: "എസ്കലേറ്റ് ചെയ്തില്ല",
  reviewedEmpty: "ഇതുവരെ ഒരു കേസും അവലോകനം ചെയ്തിട്ടില്ല.",
  sampleNote: "പേരുള്ള അഞ്ച് സാമ്പിൾ കേസുകൾ കാണിക്കുന്നു. ജനസംഖ്യാ ഫണൽ ഒരു പ്രത്യേക സിന്തറ്റിക് കൂട്ടമാണ്.",
  funnelDef: "ഫ്ലാഗ് ചെയ്തവ = പ്രീഡയബറ്റിസ് അല്ലെങ്കിൽ റഫറൽ പരിധിയിലെ ഫലം. സ്ഥിരീകരിച്ചവ = രോഗി ഫോളോ-അപ്പ് പ്ലാൻ അംഗീകരിച്ചു.",
  largestLoss: "ഫണലിലെ ഏറ്റവും വലിയ കുറവ്: {from} → {to} — {n} പേർ ({p}%) {why}.",
  lossNotFlagged: "നിർവചിച്ച പരിധികൾ അനുസരിച്ച് ഫ്ലാഗ് ചെയ്യപ്പെട്ടില്ല",
  lossGeneric: "അടുത്ത ഘട്ടത്തിലേക്ക് തുടർന്നില്ല",
  mohap: "MOHAP-ന്റെ ദേശീയ ക്യാമ്പെയ്‌നിൽ, പ്രീഡയബറ്റിക് എന്ന് ഫ്ലാഗ് ചെയ്തശേഷം ജീവിതശൈലി മാർഗനിർദേശം പാലിച്ചവരിൽ 8.1% ആറ് മാസത്തിനുള്ളിൽ സാധാരണ HbA1c-ലേക്ക് മടങ്ങി, 1% ടൈപ്പ് 2 പ്രമേഹത്തിലേക്ക് പുരോഗമിച്ചു.",
  auditRecordedD: "{test} {value} സ്ക്രീനിംഗ് ലാബിൽ നിന്ന് ലഭിച്ച് കേസിൽ ചേർത്തു.",
};
export const demoCopy: Record<Lang, D> = { en, ar, hi, ur, tl, ml };
export type DemoText = D;
export const useDemoText = () => demoCopy[useLang().lang];
