import { useLang, type Lang } from "@/lib/i18n";

// Patient-safety wording for My case: medicines on record, state-driven notifications,
// decision transparency, Emirates ID, reminder preference and clock anchoring.
const en = {
  medsOnRecord: "Medicines on record",
  medsNote: "Shown to your care team as context. This app does not prescribe or send dose reminders.",
  noMedsOnRecord: "No medicines on record.",
  notifGeneric: "Health follow-up waiting",
  notifGenericDesc: "You have an important health follow-up waiting.",
  notifReview: "Review in process",
  notifReviewDesc: "Your care team is reviewing your case. You'll be told when it's done.",
  notifAppt: "Next appointment",
  notifApptDesc: "Your appointment is booked at the location you chose.",
  noNotifications: "No notifications. Nothing to follow up.",
  tlConfirmedD: "You accepted the plan. This stops the day 3, 7 and 14 reminders and does nothing else.",
  tlNextApptD: "The 3, 6 and 12-month clinical clock starts when your visit is marked Completed.",
  clockAnchor: "Counts from the completed consultation, not from pressing “Follow-up confirmed”.",
  clockStarted: "Clinical clock started: {date}",
  clockNotStarted: "Not started — waits for a completed visit.",
  day: "Day {n}",
  eidPlaceholder: "784-0000-0000000-0",
  eidNote: "Demo only — do not enter a real Emirates ID. Nothing is saved or sent.",
  errEid: "Emirates ID format: 784-YYYY-NNNNNNN-C (15 digits).",
  optional: "optional",
  reminderPref: "Send me follow-up reminders",
  reminderPrefNote: "Reminders never include medical details.",
  on: "On", off: "Off",
  howDecided: "How this decision was made",
  resultSource: "Result source", manualEntry: "Manual entry",
  ai: "AI", notUsed: "Not used",
  decisionMaker: "Decision maker", ruleEngine: "Rule engine, {rule} v1.0",
  humanReview: "Human review", reviewRequired: "Required (RULE-003)", reviewNotRequired: "Not required", reviewReferral: "Referral (RULE-002)",
  askTitle: "Ask about your pathway",
  askDesc: "Questions are limited to explaining your approved pathway and are routed to your care team.",
  askBoundary: "I can explain your pathway. I can't diagnose or give medical advice.",
  ramadan: "Opening hours may change during Ramadan.",
  fasting: "Fasting can affect glucose readings.",
  tlReminder: "Reminders scheduled (Day 3 · 7 · 14)",
  tlAwaitingD: "Confirming stops the day 3, 7 and 14 reminders. It does not start the clinical schedule; that starts when your visit is marked Completed.",
  remindersStopped: "Reminders stopped.",
};
type P = typeof en;
const ar: P = {
  medsOnRecord: "الأدوية المسجلة",
  medsNote: "تُعرض لفريق الرعاية كسياق فقط. لا يصف هذا التطبيق الأدوية ولا يرسل تذكيرات بالجرعات.",
  noMedsOnRecord: "لا توجد أدوية مسجلة.",
  notifGeneric: "متابعة صحية بانتظارك",
  notifGenericDesc: "لديك متابعة صحية مهمة بانتظارك.",
  notifReview: "المراجعة جارية",
  notifReviewDesc: "يراجع فريق الرعاية حالتك. سيتم إبلاغك عند الانتهاء.",
  notifAppt: "الموعد القادم",
  notifApptDesc: "تم حجز موعدك في الموقع الذي اخترته.",
  noNotifications: "لا توجد إشعارات. لا شيء للمتابعة.",
  tlConfirmedD: "قبلت الخطة. هذا يوقف تذكيرات اليوم 3 و7 و14 ولا يفعل شيئاً آخر.",
  tlNextApptD: "يبدأ الجدول السريري 3 و6 و12 شهراً عند تسجيل زيارتك كمكتملة.",
  clockAnchor: "يُحتسب من الاستشارة المكتملة، وليس من الضغط على «تم تأكيد المتابعة».",
  clockStarted: "بدأ الجدول السريري: {date}",
  clockNotStarted: "لم يبدأ — بانتظار زيارة مكتملة.",
  day: "اليوم {n}",
  eidPlaceholder: "784-0000-0000000-0",
  eidNote: "تجريبي فقط — لا تُدخل هوية إماراتية حقيقية. لا يتم حفظ أو إرسال أي شيء.",
  errEid: "صيغة الهوية الإماراتية: 784-YYYY-NNNNNNN-C (15 رقماً).",
  optional: "اختياري",
  reminderPref: "أرسل لي تذكيرات المتابعة",
  reminderPrefNote: "لا تتضمن التذكيرات أي تفاصيل طبية أبداً.",
  on: "تشغيل", off: "إيقاف",
  howDecided: "كيف اتُّخذ هذا القرار",
  resultSource: "مصدر النتيجة", manualEntry: "إدخال يدوي",
  ai: "الذكاء الاصطناعي", notUsed: "غير مستخدم",
  decisionMaker: "صاحب القرار", ruleEngine: "محرك القواعد، {rule} v1.0",
  humanReview: "المراجعة البشرية", reviewRequired: "مطلوبة (RULE-003)", reviewNotRequired: "غير مطلوبة", reviewReferral: "إحالة (RULE-002)",
  askTitle: "اسأل عن مسارك",
  askDesc: "تقتصر الأسئلة على شرح مسارك المعتمد وتُحوَّل إلى فريق الرعاية.",
  askBoundary: "يمكنني شرح مسارك. لا يمكنني التشخيص أو تقديم نصيحة طبية.",
  ramadan: "قد تتغير ساعات العمل خلال شهر رمضان.",
  fasting: "قد يؤثر الصيام على قراءات الجلوكوز.",
  tlReminder: "التذكيرات مجدولة (اليوم 3 · 7 · 14)",
  tlAwaitingD: "التأكيد يوقف تذكيرات اليوم 3 و7 و14. لا يبدأ الجدول السريري؛ يبدأ عندما تُسجَّل زيارتك كمكتملة.",
  remindersStopped: "تم إيقاف التذكيرات.",
};
const hi: P = {
  medsOnRecord: "रिकॉर्ड में दवाएँ",
  medsNote: "आपकी देखभाल टीम को केवल संदर्भ के लिए दिखाई जाती हैं। यह ऐप दवा नहीं लिखता और खुराक रिमाइंडर नहीं भेजता।",
  noMedsOnRecord: "रिकॉर्ड में कोई दवा नहीं।",
  notifGeneric: "स्वास्थ्य फ़ॉलो-अप बाकी है",
  notifGenericDesc: "आपका एक ज़रूरी स्वास्थ्य फ़ॉलो-अप बाकी है।",
  notifReview: "समीक्षा जारी है",
  notifReviewDesc: "आपकी देखभाल टीम आपके केस की समीक्षा कर रही है। पूरा होने पर आपको बताया जाएगा।",
  notifAppt: "अगली अपॉइंटमेंट",
  notifApptDesc: "आपकी अपॉइंटमेंट आपके चुने स्थान पर बुक है।",
  noNotifications: "कोई सूचना नहीं। कोई फ़ॉलो-अप नहीं।",
  tlConfirmedD: "आपने योजना स्वीकार की। इससे दिन 3, 7 और 14 के रिमाइंडर रुक जाते हैं, और कुछ नहीं बदलता।",
  tlNextApptD: "3, 6 और 12 महीने की क्लिनिकल घड़ी विज़िट पूरी दर्ज होने पर शुरू होती है।",
  clockAnchor: "पूरे हुए परामर्श से गिनी जाती है, “फ़ॉलो-अप की पुष्टि” दबाने से नहीं।",
  clockStarted: "क्लिनिकल घड़ी शुरू: {date}",
  clockNotStarted: "शुरू नहीं — पूरी विज़िट का इंतज़ार।",
  day: "दिन {n}",
  eidPlaceholder: "784-0000-0000000-0",
  eidNote: "केवल डेमो — असली एमिरेट्स आईडी न डालें। कुछ भी सहेजा या भेजा नहीं जाता।",
  errEid: "एमिरेट्स आईडी प्रारूप: 784-YYYY-NNNNNNN-C (15 अंक)।",
  optional: "वैकल्पिक",
  reminderPref: "मुझे फ़ॉलो-अप रिमाइंडर भेजें",
  reminderPrefNote: "रिमाइंडर में कभी चिकित्सा जानकारी नहीं होती।",
  on: "चालू", off: "बंद",
  howDecided: "यह निर्णय कैसे लिया गया",
  resultSource: "परिणाम स्रोत", manualEntry: "मैन्युअल प्रविष्टि",
  ai: "AI", notUsed: "उपयोग नहीं हुआ",
  decisionMaker: "निर्णयकर्ता", ruleEngine: "नियम इंजन, {rule} v1.0",
  humanReview: "मानवीय समीक्षा", reviewRequired: "ज़रूरी (RULE-003)", reviewNotRequired: "ज़रूरी नहीं", reviewReferral: "रेफ़रल (RULE-002)",
  askTitle: "अपने पाथवे के बारे में पूछें",
  askDesc: "प्रश्न केवल आपके स्वीकृत पाथवे को समझाने तक सीमित हैं और आपकी देखभाल टीम को भेजे जाते हैं।",
  askBoundary: "मैं आपका पाथवे समझा सकता हूँ। मैं निदान या चिकित्सा सलाह नहीं दे सकता।",
  ramadan: "रमज़ान के दौरान खुलने का समय बदल सकता है।",
  fasting: "उपवास ग्लूकोज़ रीडिंग को प्रभावित कर सकता है।",
  tlReminder: "रिमाइंडर निर्धारित (दिन 3 · 7 · 14)",
  tlAwaitingD: "पुष्टि करने से दिन 3, 7 और 14 के रिमाइंडर रुक जाते हैं। इससे क्लिनिकल शेड्यूल शुरू नहीं होता; वह तब शुरू होता है जब आपकी विज़िट पूर्ण चिह्नित होती है।",
  remindersStopped: "रिमाइंडर बंद हो गए।",
};
const ur: P = {
  medsOnRecord: "ریکارڈ میں ادویات",
  medsNote: "آپ کی نگہداشت ٹیم کو صرف سیاق کے طور پر دکھائی جاتی ہیں۔ یہ ایپ دوا تجویز نہیں کرتی اور خوراک کی یاد دہانی نہیں بھیجتی۔",
  noMedsOnRecord: "ریکارڈ میں کوئی دوا نہیں۔",
  notifGeneric: "صحت کا فالو اپ باقی ہے",
  notifGenericDesc: "آپ کا ایک اہم صحت فالو اپ باقی ہے۔",
  notifReview: "جائزہ جاری ہے",
  notifReviewDesc: "آپ کی نگہداشت ٹیم آپ کے کیس کا جائزہ لے رہی ہے۔ مکمل ہونے پر آپ کو بتایا جائے گا۔",
  notifAppt: "اگلی اپائنٹمنٹ",
  notifApptDesc: "آپ کی اپائنٹمنٹ آپ کے منتخب مقام پر بک ہے۔",
  noNotifications: "کوئی اطلاع نہیں۔ کوئی فالو اپ نہیں۔",
  tlConfirmedD: "آپ نے منصوبہ قبول کیا۔ اس سے دن 3، 7 اور 14 کی یاد دہانیاں رک جاتی ہیں، اور کچھ نہیں بدلتا۔",
  tlNextApptD: "3، 6 اور 12 ماہ کی طبی گھڑی وزٹ مکمل درج ہونے پر شروع ہوتی ہے۔",
  clockAnchor: "مکمل مشاورت سے شمار ہوتی ہے، “فالو اپ کی تصدیق” دبانے سے نہیں۔",
  clockStarted: "طبی گھڑی شروع: {date}",
  clockNotStarted: "شروع نہیں — مکمل وزٹ کا انتظار۔",
  day: "دن {n}",
  eidPlaceholder: "784-0000-0000000-0",
  eidNote: "صرف ڈیمو — اصل ایمریٹس آئی ڈی درج نہ کریں۔ کچھ محفوظ یا ارسال نہیں ہوتا۔",
  errEid: "ایمریٹس آئی ڈی فارمیٹ: 784-YYYY-NNNNNNN-C (15 ہندسے)۔",
  optional: "اختیاری",
  reminderPref: "مجھے فالو اپ یاد دہانیاں بھیجیں",
  reminderPrefNote: "یاد دہانیوں میں کبھی طبی تفصیلات نہیں ہوتیں۔",
  on: "آن", off: "آف",
  howDecided: "یہ فیصلہ کیسے ہوا",
  resultSource: "نتیجے کا ذریعہ", manualEntry: "دستی اندراج",
  ai: "AI", notUsed: "استعمال نہیں ہوا",
  decisionMaker: "فیصلہ ساز", ruleEngine: "اصول انجن، {rule} v1.0",
  humanReview: "انسانی جائزہ", reviewRequired: "ضروری (RULE-003)", reviewNotRequired: "ضروری نہیں", reviewReferral: "ریفرل (RULE-002)",
  askTitle: "اپنے راستے کے بارے میں پوچھیں",
  askDesc: "سوالات صرف آپ کے منظور شدہ راستے کی وضاحت تک محدود ہیں اور آپ کی نگہداشت ٹیم کو بھیجے جاتے ہیں۔",
  askBoundary: "میں آپ کا راستہ سمجھا سکتا ہوں۔ میں تشخیص یا طبی مشورہ نہیں دے سکتا۔",
  ramadan: "رمضان کے دوران اوقاتِ کار بدل سکتے ہیں۔",
  fasting: "روزہ گلوکوز ریڈنگ پر اثر ڈال سکتا ہے۔",
  tlReminder: "یاد دہانیاں طے شدہ (دن 3 · 7 · 14)",
  tlAwaitingD: "تصدیق کرنے سے دن 3، 7 اور 14 کی یاد دہانیاں رک جاتی ہیں۔ اس سے طبی شیڈول شروع نہیں ہوتا؛ وہ تب شروع ہوتا ہے جب آپ کی وزٹ مکمل درج ہو۔",
  remindersStopped: "یاد دہانیاں بند ہو گئیں۔",
};
const tl: P = {
  medsOnRecord: "Mga gamot na nakatala",
  medsNote: "Ipinapakita sa iyong care team bilang konteksto. Hindi nagrereseta ang app na ito at hindi nagpapadala ng paalala sa dosis.",
  noMedsOnRecord: "Walang gamot na nakatala.",
  notifGeneric: "May naghihintay na follow-up",
  notifGenericDesc: "Mayroon kang mahalagang health follow-up na naghihintay.",
  notifReview: "Isinasagawa ang repaso",
  notifReviewDesc: "Nirerepaso ng iyong care team ang kaso mo. Sasabihan ka kapag tapos na.",
  notifAppt: "Susunod na appointment",
  notifApptDesc: "Naka-book ang appointment mo sa lokasyong pinili mo.",
  noNotifications: "Walang abiso. Walang kailangang follow-up.",
  tlConfirmedD: "Tinanggap mo ang plano. Pinapahinto nito ang paalala sa araw 3, 7 at 14 at wala nang iba.",
  tlNextApptD: "Magsisimula ang 3, 6 at 12 buwang clinical clock kapag Nakumpleto ang pagbisita mo.",
  clockAnchor: "Binibilang mula sa natapos na konsultasyon, hindi sa pagpindot ng “Nakumpirma ang follow-up”.",
  clockStarted: "Nagsimula ang clinical clock: {date}",
  clockNotStarted: "Hindi pa nagsisimula — hinihintay ang natapos na pagbisita.",
  day: "Araw {n}",
  eidPlaceholder: "784-0000-0000000-0",
  eidNote: "Demo lamang — huwag maglagay ng totoong Emirates ID. Walang sine-save o ipinapadala.",
  errEid: "Format ng Emirates ID: 784-YYYY-NNNNNNN-C (15 digit).",
  optional: "opsyonal",
  reminderPref: "Padalhan ako ng paalala sa follow-up",
  reminderPrefNote: "Hindi kailanman may medikal na detalye ang mga paalala.",
  on: "Bukas", off: "Sarado",
  howDecided: "Paano ginawa ang desisyong ito",
  resultSource: "Pinagmulan ng resulta", manualEntry: "Manwal na paglalagay",
  ai: "AI", notUsed: "Hindi ginamit",
  decisionMaker: "Nagpasya", ruleEngine: "Rule engine, {rule} v1.0",
  humanReview: "Repaso ng tao", reviewRequired: "Kailangan (RULE-003)", reviewNotRequired: "Hindi kailangan", reviewReferral: "Referral (RULE-002)",
  askTitle: "Magtanong tungkol sa iyong pathway",
  askDesc: "Limitado ang tanong sa pagpapaliwanag ng aprubadong pathway mo at ipinapasa sa iyong care team.",
  askBoundary: "Kaya kong ipaliwanag ang pathway mo. Hindi ako makakapag-diagnose o magbigay ng medikal na payo.",
  ramadan: "Maaaring magbago ang oras ng pagbubukas tuwing Ramadan.",
  fasting: "Maaaring makaapekto ang pag-aayuno sa glucose reading.",
  tlReminder: "Naka-iskedyul ang mga paalala (Araw 3 · 7 · 14)",
  tlAwaitingD: "Ang pagkumpirma ay humihinto sa mga paalala sa araw 3, 7 at 14. Hindi nito sinisimulan ang klinikal na iskedyul; magsisimula iyon kapag minarkahang Completed ang iyong pagbisita.",
  remindersStopped: "Huminto na ang mga paalala.",
};
const ml: P = {
  medsOnRecord: "രേഖപ്പെടുത്തിയ മരുന്നുകൾ",
  medsNote: "നിങ്ങളുടെ കെയർ ടീമിന് സന്ദർഭത്തിനായി മാത്രം കാണിക്കുന്നു. ഈ ആപ്പ് മരുന്ന് നിർദ്ദേശിക്കുകയോ ഡോസ് ഓർമ്മപ്പെടുത്തൽ അയയ്ക്കുകയോ ചെയ്യുന്നില്ല.",
  noMedsOnRecord: "രേഖപ്പെടുത്തിയ മരുന്നുകളില്ല.",
  notifGeneric: "ആരോഗ്യ ഫോളോ-അപ്പ് കാത്തിരിക്കുന്നു",
  notifGenericDesc: "നിങ്ങൾക്ക് പ്രധാനപ്പെട്ട ഒരു ആരോഗ്യ ഫോളോ-അപ്പ് കാത്തിരിക്കുന്നു.",
  notifReview: "അവലോകനം നടക്കുന്നു",
  notifReviewDesc: "നിങ്ങളുടെ കെയർ ടീം കേസ് അവലോകനം ചെയ്യുന്നു. കഴിയുമ്പോൾ അറിയിക്കും.",
  notifAppt: "അടുത്ത അപ്പോയിന്റ്മെന്റ്",
  notifApptDesc: "നിങ്ങൾ തിരഞ്ഞെടുത്ത സ്ഥലത്ത് അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്തു.",
  noNotifications: "അറിയിപ്പുകളില്ല. ഫോളോ-അപ്പ് ആവശ്യമില്ല.",
  tlConfirmedD: "നിങ്ങൾ പ്ലാൻ അംഗീകരിച്ചു. ഇത് ദിവസം 3, 7, 14 ഓർമ്മപ്പെടുത്തലുകൾ നിർത്തുന്നു, മറ്റൊന്നും ചെയ്യുന്നില്ല.",
  tlNextApptD: "സന്ദർശനം പൂർത്തിയായി എന്ന് രേഖപ്പെടുത്തുമ്പോൾ 3, 6, 12 മാസ ക്ലിനിക്കൽ ക്ലോക്ക് ആരംഭിക്കുന്നു.",
  clockAnchor: "പൂർത്തിയായ കൺസൾട്ടേഷനിൽ നിന്ന് എണ്ണുന്നു, “ഫോളോ-അപ്പ് സ്ഥിരീകരിച്ചു” അമർത്തുന്നതിൽ നിന്നല്ല.",
  clockStarted: "ക്ലിനിക്കൽ ക്ലോക്ക് ആരംഭിച്ചു: {date}",
  clockNotStarted: "ആരംഭിച്ചിട്ടില്ല — പൂർത്തിയായ സന്ദർശനത്തിനായി കാത്തിരിക്കുന്നു.",
  day: "ദിവസം {n}",
  eidPlaceholder: "784-0000-0000000-0",
  eidNote: "ഡെമോ മാത്രം — യഥാർത്ഥ എമിറേറ്റ്സ് ഐഡി നൽകരുത്. ഒന്നും സേവ് ചെയ്യുകയോ അയയ്ക്കുകയോ ഇല്ല.",
  errEid: "എമിറേറ്റ്സ് ഐഡി ഫോർമാറ്റ്: 784-YYYY-NNNNNNN-C (15 അക്കങ്ങൾ).",
  optional: "ഐച്ഛികം",
  reminderPref: "ഫോളോ-അപ്പ് ഓർമ്മപ്പെടുത്തലുകൾ അയയ്ക്കുക",
  reminderPrefNote: "ഓർമ്മപ്പെടുത്തലുകളിൽ ഒരിക്കലും മെഡിക്കൽ വിവരങ്ങൾ ഉണ്ടാകില്ല.",
  on: "ഓൺ", off: "ഓഫ്",
  howDecided: "ഈ തീരുമാനം എങ്ങനെ എടുത്തു",
  resultSource: "ഫലത്തിന്റെ ഉറവിടം", manualEntry: "മാനുവൽ എൻട്രി",
  ai: "AI", notUsed: "ഉപയോഗിച്ചിട്ടില്ല",
  decisionMaker: "തീരുമാനമെടുത്തത്", ruleEngine: "റൂൾ എഞ്ചിൻ, {rule} v1.0",
  humanReview: "മനുഷ്യ അവലോകനം", reviewRequired: "ആവശ്യമാണ് (RULE-003)", reviewNotRequired: "ആവശ്യമില്ല", reviewReferral: "റഫറൽ (RULE-002)",
  askTitle: "നിങ്ങളുടെ പാത്ത്‌വേയെക്കുറിച്ച് ചോദിക്കുക",
  askDesc: "ചോദ്യങ്ങൾ അംഗീകൃത പാത്ത്‌വേ വിശദീകരിക്കുന്നതിൽ മാത്രം പരിമിതമാണ്, കെയർ ടീമിലേക്ക് അയയ്ക്കുന്നു.",
  askBoundary: "എനിക്ക് നിങ്ങളുടെ പാത്ത്‌വേ വിശദീകരിക്കാം. രോഗനിർണയം നടത്താനോ മെഡിക്കൽ ഉപദേശം നൽകാനോ കഴിയില്ല.",
  ramadan: "റമദാനിൽ പ്രവർത്തന സമയം മാറിയേക്കാം.",
  fasting: "ഉപവാസം ഗ്ലൂക്കോസ് റീഡിംഗുകളെ ബാധിച്ചേക്കാം.",
  tlReminder: "ഓർമ്മപ്പെടുത്തലുകൾ ഷെഡ്യൂൾ ചെയ്തു (ദിവസം 3 · 7 · 14)",
  tlAwaitingD: "സ്ഥിരീകരിക്കുന്നത് ദിവസം 3, 7, 14 ഓർമ്മപ്പെടുത്തലുകൾ നിർത്തുന്നു. ഇത് ക്ലിനിക്കൽ ഷെഡ്യൂൾ ആരംഭിക്കുന്നില്ല; നിങ്ങളുടെ സന്ദർശനം പൂർത്തിയായതായി അടയാളപ്പെടുത്തുമ്പോഴാണ് അത് ആരംഭിക്കുന്നത്.",
  remindersStopped: "ഓർമ്മപ്പെടുത്തലുകൾ നിർത്തി.",
};
export const patientCopy: Record<Lang, P> = { en, ar, hi, ur, tl, ml };
export const usePatientText = () => patientCopy[useLang().lang];
